### ISSUE TITLE
cue_script.model is incompletely ported to 1.0

### ISSUE THREAD

**Issue by bltzr** [jamoma/JamomaMax#1004]
Reinhold's feedback from the user list:

1. pushing [load script] in the [cue_script.view] bpatcher do nothing, no file to choose, same for [save script], also the [script/read] to the cue_script.model do nothing
2. only drop a file in the view-bpatcher load the script.
3. the message-box in cue_script.model.maxhelp is connect to left inlet, it should be in the right inlet ?
4. In the cue_script.model.maxhelp - tab - Edit with, there is a typo with instead of width
4. Editing in Textmate works (after "script/edit with Textmate" command), but in Textmate "show CUE List" gives a "Failure...." - message

**Comment by ricardo78** [comment]
I can confirm this as well.

**Comment by lossius** [comment]
Number 3 was addressed by @matcham in 469ccc31846d9c15ef13f6c50798b774df5fd130

**Comment by lossius** [comment]
I believe all issues are resolved now.
