### ISSUE TITLE
j.model crashes max if jamoma is not instantiate 

### ISSUE THREAD

**Issue by blueyeti** [jamoma/JamomaMax#1008]
To reproduce it :
Open max7, create object j.model -> crash (both mac and windows)
or open max and open condition.model -> crash 

Trick before solving this issue : put a "j.receive model:address" in the same patcher at the left of j.model

Jean-Michel

**Comment by bltzr** [comment]
Hi @blueyeti ! Did you follow this: https://github.com/jamoma/JamomaMax#quickstart ?
Because it looks as if you didn't have j.loader loaded at startup...

**Comment by bltzr** [comment]
You could also install Jamoma from Max7's packageManager: this is the easiest, more seamless way to use Jamoma...

**Comment by blueyeti** [comment]
Damn... Series of mistakes and strange : 
from the package manager, .mxo appears as folders on my mac (because of missing Pkginfo file in the mxo) and I haven't add this file on the j.loader that is in the extensions folder. On PC I forget to copy the extensions folder.

**Comment by bltzr** [comment]
glad to know it now works for you
