### ISSUE TITLE
document j.namespace's @update attribute

### ISSUE THREAD

**Issue by bltzr** [jamoma/JamomaMax#1010]
Description of the problem.

j.namespace @update attribute is set to 1 by default.
This causes the result of the set request to j.namespace to be output every time there is a change in the chosen namespace (i.e. each a parameter or a model is added or removed). 
This is sometimes handy, but that can also cause some pretty heavy pressure when loading a (big) patcher, because each and every added model or parameter causes the results of each and every j.namespace to be output, which can become a problem when a lot of models and j.namespaces are present in a patcher.

I had this problem once, and changing @update 0 to all j.namespaces dramatically improved the loadtime.

**Comment by jln-** [comment]
fixed in https://github.com/jamoma/JamomaMax/commit/cb793c9fdb93b9c45343e84df5b46c667a4102e4
