### ISSUE TITLE
mapper.model input and output addresses not stored by cue_manager

### ISSUE THREAD

**Issue by evanmtp** [jamoma/JamomaMax#1011]
When working with mapper.model, I noticed that the input and output parameters (i.e., the params that specify which parameter is to be mapped to which other parameter) are not saved in cue_manager cues. This is particularly strange because the parameters do show up in cue_manager's pop-out menu:

<img width="381" alt="screen shot 2016-08-08 at 3 17 39 pm" src="https://cloud.githubusercontent.com/assets/5342408/17493263/88ed6ac0-5d7d-11e6-9e4d-2d0c2bb18021.png">

When a cue is stored, however, the input and output parameters are not included. I'm copying the mapper section of a cue below, and you'll notice that the input and output parameters that should contain the addresses are absent:

/mapper_help/input/going.down/action.1 none
/mapper_help/input/going.down/action.2 none
/mapper_help/input/going.down/action.3 none
/mapper_help/input/going.up/action.1 none
/mapper_help/input/going.up/action.2 none
/mapper_help/input/going.up/action.3 none
/mapper_help/input/threshold/active 0
/mapper_help/input/threshold.down 0.000000
/mapper_help/input/threshold.up 1.000000
/mapper_help/input/index 0
/mapper_help/input/max 1.000000
/mapper_help/input/min 0.000000
/mapper_help/output/going.down/action.1 none
/mapper_help/output/going.down/action.2 none
/mapper_help/output/going.down/action.3 none
/mapper_help/output/going.up/action.1 none
/mapper_help/output/going.up/action.2 none
/mapper_help/output/going.up/action.3 none
/mapper_help/output/threshold/active 0
/mapper_help/output/threshold.down 0.000000
/mapper_help/output/threshold.up 1.000000
/mapper_help/output/index 0
/mapper_help/output/max 24.000000
/mapper_help/output/min -24.000000
/mapper_help/output/unit none
/mapper_help/data/active 1
/mapper_help/data/bypass 0
/mapper_help/function linear
/mapper_help/clipmode both
/mapper_help/rampTime 0

Example patcher:

<pre><code>
----------begin_max5_patcher----------
1877.3oc6ZsziaaCD9r2eEDJGJJpiW8vOSOEzVfdnnOPysrAFzRz1LQhTUjZ
ezfze6cHodPIYY60qcfODDDYuCEIGNey2LbH8muYfyJ9iDgC5Mn2iFL3y2LX
fVjRvfh+dfSB9wvXrP+ZNg7jDBS5Lzzlj7nTK+237OgnLjbKAcmyObmCJkm9
ZdtDAud9HzuykDnQrT8FYDDF9OLNYTh.slmgtMAmlRxVtkDmdKkkBcDyhZJF
FMP9nx4NlxHg7blVA7KDJjOESzZT4qwxSnrXhTq+dEBSwxvsT1lkYjPoY8Ow
ycj6Pz3IpmAEeDLxE8g5ABzfxQxsPJMROa7Ue70ddkyYZFQ.qNrjxY1Sg675
ovs3A5Cp97katQ8X3KDF9oXZ3m..fDQk.FH4nvsDPhBVB4LIzGAhu1724DQW
fgJPLtFZdpOfoszuJ3hWvoCLKbNil3eljvYBYlFbQZEFI1xe.zZzp7MJR.n7
33Xkc1XlFkviHwem.U6XyyUeKEmgSHRRl.cOEqPjkIXFdCIyfNNuXqmm1bYd
NMPaI8ceVN0tmSi26.uJAQJUFq7TTDc8ZvoiIMVlWK4u13LoMbvKIzFKA9dU
G.GzDDVT33dG6WFsYzati488ld+FvqjmKHZexTtfp.naebHxLjPyjvsbiK6Z
ZLX0uccF4exIrvmti4u2Q4o8MJavT1cv+d2VBD.TsBefZ.BzJh7ABgUw2TdG
1nLPPEDfzYXj1tGxV9Gp.lF+JRztoZydwNKSmZbPlncWF6MU6639r7WleJtK
qzJCIqTgwLF2D8T2LiyHkMcOk7v8TAcEMlJexdAwWuFbsLqj5fqkVJd3mHQQ
Y3MhvLdbrs1GpBZJ2lwy2r0VNggWES11sClFtuaCq1nX5Mjvyhf0kkDi4S9T
JwnpNNUJINaSQxXmJePGaS+wQ4Wngux3lSzeLqePzqKH5GbfLYA9KLgR5eN.
GW83oWIiTv1H.yA88TbPXjG.8pG2i+vPVnLHeUhIr75LdBROycBAYzGcDYTs
U9vfyKMFbIdLNPa47eV3g62XUmCVUUn6SlUELy7Qgiu6jmCLdHV0j4l.uyVz
+bTRqTKk+6hRq9aHuCA1JHLQ.QIJOlLpCYxnEFxTswsOLQP2vvwNCs+1QSv7
ODAq.Z7LYu1CAKnKxL8a7qyRVq5pBNYFV4tOlbJLrwGrBL8f5Gz+TTk2xr08
KICSUkFBi.+D0FAUeDgk3x891MykUwDHaScuXzvSHA1ZnLw03vF9C6BsBr.K
uhMNZy4Tiif9u5wwCZXmPneWHbli0.TgFuMiBwKdw.PksLE1t.Udj0W4dv5q
JJNc5Ah7ri8K66XO3FR2fp0BXEn.mEJ.nvmo.k.WozTKwCr5hx.7QdlUIAJQ
TlQjeknLhJhjo+AURwYvRTBqu7LiE4wokjJ0v.9dYrbpVULBAn3lxArhlsvP
rFqK6br4fUlaEYSEzwDbyxr.dvoDFTDjE2sQyQj037X4xc6Z0r8VtvMarkaU
4qrIiFwYJkngoVItb5rqntdwneCFNcGcFvXvrzSiBXQlKVgyz4FLtfk.jijy
ia1TU+hIqkEMCQJXsrhRdZ+MlQ2rcO8cEGZLYeistEwxblo0k.SStDpPuo0V
BEpVP8ZN7OhYTXS5DI0.APIDkM1IykWyVteGsDANwgjGnQRSRPamA30ooUAa
qP4H5FhP1TlDaxgUKoSHAPTdYF+kRRRZLrJZ9BMNMUaFocPpFxaErJgHD3Mj
J9lcDKOao8mNtGkuusS0abMylO8mp81WzI79dBw2el5NmszTmVi1Nh2OnLle
QvlSzz1HOPSK6GGAgahP2ZcvLly2wbdKmW6tWqUb63TG.OlahrNe7kAPBtR.
DXgSn2S1IlfitMpdq06YmOC+5COAyM3RvKCdB5Ad7ut4Kp8pbKXc1dUQYbWL
Zl2X+EiAdyhYWFdi2UAvDxSVQgpH9y29te09XlWVTrvp7MizGdt7Q4goOWlL
Jdy7Gs.fiYSUQyl7xfC+cCGWKoUTkX.yGrR1AaAM1087xSbOMdRYUvlOVr3x
vPb+5gI6aWTm+nS9Gk00erxqOvcl5JLuHV34WEN8xsTQyiE6LFgw6nL0i04f
mt3hDZ4PYfsWPE0DAq1W86p0aCaCx4GUOd0eodBoSMRL+X.ZAS00YptuudJv
POvp12M9I34YgkpSg6BpooAJXRRYUUc+9pEbq2aKMJhvZGXIhJT0nYpV7n70
dtZ7ziTiUIiuRTYkwy6HT4oWMZr2QakCtdzY+iUmuhrytGoNO+LoxEQVJOsN
czonklSmZIVJynqxklfK1G+3y5TT1DyWgiKBwUEXbeGoR84tbSs9dNOhc6Kg
odex0aEq3zzau4r89aY5BdIwlecSd95xTBdVW8g2jucGV69Nr75dQUcv6cea
UtG71pF235fmM4Y8SqxoR4C4wlimWY.WDLyexjg87s5Inm63xs5WW3tUqRdo
MKnma4R2o1W0fxMp0ULz55E5d0B8esBsuRAXl+xM+Orz+emO
-----------end_max5_patcher-----------
</code></pre>

[cue_manager_mapper_bug.cues.txt]

**Comment by evanmtp** [comment]
Update: think I solved it. It seems as if cue_manager doesn't recognize a parameter if there are other parameters nested below it hierarchically. So due to the fact that we have all of these nested parameters,

input/going.down/action.1
input/going.down/action.2
input/going.down/action.3
input/going.up/action.1
input/going.up/action.2
input/going.up/action.3
input/threshold/active
input/threshold.down
input/threshold.up
input/index
input/max
input/min

it seems as if

input

is not recognized as a parameter itself. Likewise with output.

Once I renamed these parameters and their corresponding j.remotes to input/address and output/address, I was able to save and recall them with cue_manager.

I would suggest that the quickest solution to this specific would be to push this altered version of mapper. I have altered the patch and can do that, if it's desirable - I haven't committed anything to the Jamoma repo and haven't seen guidelines on contributing, so please let me know if there's anything I should read before pushing a change.

In the grander scheme, it seems like it would be preferrable for mapper to recognizes parameters regardless of whether they have other parameters nested below them, but I think resolving this goes beyond my abilities.

**Comment by bltzr** [comment]
Hi Evan !
I have given it a try, and that was also my guess... (though I got them  into j.cue, but wasn't able to get anything else than 'none' as a value of those) 
I'd suggest you do a pull request, so that @jln- can review your changes (he's the author of this model), and make sure it doesn't break anything on his side... or fix the broken things...
Anyway, this comes perfectly in time, as we are preparing for the 1.0.2 fix release !

**Comment by evanmtp** [comment]
Hi Pascal, thanks for your response! I'll do just that.

Best,

Evan

**Comment by jln-** [comment]
Hi Evan,

Thanks for your report. Indeed I encountered this bug a while back and @theod fixed this.

I guess you and Pascal tested using the version from the package manager ? I just gave it a test using latest nightly build from jamoma.org (http://jamoma.org) and it seems to work ok. Can you or Pascal give it a test ?

Best,
Julien

--

**Comment by evanmtp** [comment]
Hi Julien,

I just tried it out with the latest nightly and can report that it's
resolved. I'll check the nightlies next time before filing a bug report.
Thanks for your work!

Best,

Evan

**Comment by jln-** [comment]
Fixed in current nightly builds.
