### ISSUE TITLE
DBAP model scene view not working

### ISSUE THREAD

**Issue by tonetechnician** [jamoma/JamomaMax#1021]
Hey! 

Wondering if someone could help me. I'm wanting to play with the DBAP model that you've built. I've been using the help example to get me going, but it doesn't seem to be working as it should. My scene view just displays this:

![screen shot 2017-10-10 at 8 39 16 pm](https://user-images.githubusercontent.com/13471797/31404024-236c8eae-adfb-11e7-931d-48a326a9d1b0.png)

![screen shot 2017-10-10 at 8 39 45 pm](https://user-images.githubusercontent.com/13471797/31404041-2e3bf158-adfb-11e7-908f-d42455f4d576.png)

Any idea why?

Thanks!

**Comment by tap** [comment]
The `ambimonitor` (and other related objects) are part of the ICST package. You can install this from Max's Package Manager.

Hope that helps!

**Comment by tonetechnician** [comment]
Ah! Thanks so much, helps alot. All seems to be working now \:D/
