### ISSUE TITLE
mapper.model save as

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#131]
I would like to see a save as option in mapper.model

 see more on the original redmine issue http://redmine.jamoma.org/issues/1440

**Comment by reno-** [comment]
I'm not sure to understand the request.
You can save a preset of your mapping if this is what you want, or create a cue with the content of the mapping.
@lossius : Do you think this issue is still relevant?

**Comment by lossius** [comment]
Closing this issue
