### ISSUE TITLE
jmod.mapper looses its mappings. 

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#132]
Jmod mapper seems completely unreliable in retaining its mapping, when using the listening function.  Saving and recalling  from file. I have not been able to create a mapping, save it to disc and then recall it succesfully using the listening function. When deleting mappings in the text representation  and creating new ones using the listening function,  current mappings seem to be overwritten. Otherwise general strangeness.

 see more on the original redmine issue http://redmine.jamoma.org/issues/1439

**Comment by reno-** [comment]
You can save a mapping of mapper.model with a preset, and it worls
