### ISSUE TITLE
jmod.motion%, jmod.motion2% and jmod.motiongram% max errors

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#140]
when running the maxhelp for jmod.motion%, jmod.motion2% and jmod.motiongram% I get the following errors

/: doesn't understand "list"
!/: doesn't understand "list"
!/: doesn't understand "list"
jit.rgb2luma: mismatch plane

 see more on the original redmine issue http://redmine.jamoma.org/issues/1431

**Comment by reno-** [comment]
there is no more error with these files
