### ISSUE TITLE
reviewing maxobjects.com appearance

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#149]
Jamoma @ maxobjects.com ( http://tinyurl.com/nxx46k ) looks pretty outdated. 

I think the max-overview.maxpat is in a pretty good shape, so it shouldn't be too complicated to check in the current state of Jamoma.

Who volunteers for review & editing ?

 see more on the original redmine issue http://redmine.jamoma.org/issues/1422

**Comment by jln-** [comment]
maxobjects.com is closing... :-( Closed.
