### ISSUE TITLE
TextSlider Improvements

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#158]
Review the "jcom.textslider" and "textslider again" threads on the Jamoma-devel list (these pre-date the nabble archive).  We have lots of issues here, including:

* What command-key-combos to use or not use and why.
* User preference issues
* Focus
* Default snapping and jumpclick

 see more on the original redmine issue http://redmine.jamoma.org/issues/1412

**Comment by tap** [comment]
yes -- use live.numbox please
