### ISSUE TITLE
TUIO wrapper or module 

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#167]
for communicating with TUIO multitouch devices 

 see more on the original redmine issue http://redmine.jamoma.org/issues/1403

**Comment by reno-** [comment]
I assign this one to you @jln- because I remember you used TUIO for a few project. Did you use a module from your Userlib or something?
I add @matcham too, I'm pretty sure he has an opinion on that question

**Comment by matcham** [comment]
does this module/model already exist ? is there something to fix, or is it a feature request ?

receiving TUIO is very easy (= udpreceive 3333) ; but then multitouch data can be parsed and used in so many different ways, that I can't imagine one model covering all the possibilities...

**Comment by reno-** [comment]
I'm just review some old FR. So I'm closing the issue
