### ISSUE TITLE
readonly not properly implemented in jcom.parameter

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#168]
The readonly attribute implementation is lacking:

If a value is receieved in the left inlet of jcom.parameter, we get spurious OSC messages from jcom.in and jcom.hub.

As the attribute does not seem to be used anyewhere yet, I guess this is low priority....

----------begin_max5_patcher----------
520.3oc2VsrSiCCEccxWgkW2o3G4QyrhuB1fPH2DSqQI1QIthBH92G+HsSYD
DLsATG1DGe801mywWeu943H3R0VdOD7av0fnnmiihblrFhF5GAaXaKqY8N2f
2UqjaZfy7CY9UHq4Z2X3Ai2ojZIqg67+JdWESxNXBpM5cyfLX0aR+XK2CE6t
vzvY.3RlbEDbyAqbu3ImWXzbzf4VltbsPt51Ndo1uBoolQAXeSJx0oXNZ+JI
pbnSs79egyfVauDGa+LKPcPxevL4czRy251XXaGukKq.Wn485IRkvumJc7BC
A4jj7hQEljiQXZ388rU72j6jyBtW3CGHKbM4uC4w+vHOk3ncBNMD1ilv6D2W
pZla3vWcRCa9hiRYnNIII2mrHcr6DKlZcQHOakEe.CM2G2rXLYIepkk0aVdt
pKCYQ7EURyGSVNpJK+mTgcH7.mg93Rro+LykR7bGivikKkN02MZYcFJq4cfK
suxv70vFPS+pacGpfK63rJkr9Q.dhhhnidG5zxuP7EjHevaQNTDcN.qEx+8o
qtcwZ+0JauZSW4NHO7juYf+tOUFUTHYZgRdnSIuxo0hpJta7cbpQT0pDR8.H
.27lmyAioj.vT12JjBRkLwX.b3PJKYdp8zNyekgtu2Ih07PvJ5ygUJovBOZg
q1WBcw9dmHXSCAreuQeAfH5IfHSmWh+CbZuUFC
-----------end_max5_patcher-----------

 see more on the original redmine issue http://redmine.jamoma.org/issues/1402

**Comment by lossius** [comment]
I updated the test patch for 0.6/1.0 and this issue no longer seem to be relwvnt or a problem:

<pre><code>
----------begin_max5_patcher----------
625.3oc2W1rbaCBDG+rzSACmUcA8ocNkmhdoSGOXKrCdjPZP3T6lIu6EVjki
a7znpPy3IWjFfE1+7S6tfdJL.up4.uCitC8cTPvSgAAPW1NB5aGfqYGVWw5.
yvapZj6qwQtgZYJVMWyUK4R1pJt0DR+XaZjZoYTXZeiqJYR1o40rWWw05isb
muw3HDdEStEi9QuIFuHjFi.2R66rSez4DL9rYtECrKdv2pZl11S9fR0qePH2
tTwWqcNMKaFIBQcuxH1mwzYjAEX2.cheA9iZG10snDDPypceglis88bXn8Qz
HQnj+SyjOsAz7CfdvsJdKWVhz7NMdRL78wN5aQpXBvnhzqRpMr0u5y+aPuzo
PuZdWGaK+U3qjoYec0wVicHhO4Wr232Bfez34SITi5AXcifijX.Dozr2AOHd
L0a2LivwSstkmpYcMPk.DJs.dk3qDu4dEcB4sH4bgXIEtx5Klk4ExU3UxU2T
xqtAgWe4J2Qhoy8TT2jNq7Sz0M5CIo4jIeeirOcmAD6nAkPm.NR7Z13PvE5d
6UvLOMb.U2scoIHjYZq3rxFY0QD8F65YmXIsOu0WYrWbkCXsvUB4e9+Bffr8
eIz6Z1qVeZu2eY4HzYIUZXrPxzhF4KMJ8BidPTVxkuT0khNalOHRxU+7OZ8j
NB8j+gImQQGSjGh9WjSsnrsQH08ehxSgy8JxgbrhjgVm8i2zewXzO4eS+ItC
tSV.QzoIyGZ8eXCjMlMvGWz4HTSxDUiKUl019HW00ujfPLUJ20nrMKhflBoq
IrhXE+QwI6gC5vLkoVj1THZuxU65PdJ1MUycaTx8Bn5Rn0yOG9a.Y8lw2C
-----------end_max5_patcher-----------
</code></pre>
