### ISSUE TITLE
jcom.modular behavior

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#17]
I'm playing with jcom.modular for a few days, and I found some behavior inconsistent.

Here is my experience and the way I will like it will works : 

I really like that I could be able to load a file AND to declare the namespace with messages.
The XML file is really perfect for using with software that have a static namespace that could not be changed. e.g. : Modul8, Dlight etc???
The messages are useful to work with software that have a dynamic namespace like VDMX, Max, PD and many others.

 see more on the original redmine issue http://redmine.jamoma.org/issues/1592

**Comment by reno-** [comment]
j.modular will be refactor soon…
