### ISSUE TITLE
Module(s) for graphical interfacing concerning positioning o

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#172]
Module(s) for graphical interfacing concerning positioning o

 see more on the original redmine issue http://redmine.jamoma.org/issues/1397

**Comment by reno-** [comment]
This could be related to #173, but I'm not sure.
@lossius , you made this FR a few years ago. Is it still valid?

**Comment by lossius** [comment]
My guess is that I have been thinking of what we now would call a view for positioning sources and speakers etc. I'll just close it.
