### ISSUE TITLE
msg_toggle should accept bang

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#184]
It would be great if ,similar to the behavior of Max's toggle, also a
jcom.parameter with @type msg_toggle would accept a bang as input message
and modify its output accordingly. 

 see more on the original redmine issue http://redmine.jamoma.org/issues/1380

**Comment by reno-** [comment]
This can be addressed with type boolean, and with a toggle in the view

<pre><code>
----------begin_max5_patcher----------
436.3ocyTssaCBCC8Y3qHJOyl.JpqcO08cTMUEJdrTANUASW2p5+9HgKkMwz
XsqS6ABxWh8wGG6CtN7X0dnfytmsj43bv0wwpxnvoQ1gmK1uNSTXciSpzzLf
6UaBKyUkTFPViAMZ2Jn0OKwzUZXMUG7og256wBhla9E52dxdr4J0QgdcKT6O
WhU2r0pLwlaU7laB84cYQKxABzq.TDmYun+IbIwNXYzcz00b3cVko.QEIHoB
sFQEdtLvcQWJADL6Og.hKIppbOupLZxXqxXAlNXYFw+spDDdoJfsgif8Vnx2
bqFxUDvxKRW8w18SJjJjuYwXfofFhDh9ZRX9jSs5fwvBbudeC9puOzvptt0x
CZoH65yScuy5QUrEF3yhUpLPfrEIvShxLhE7i3vvucgQC6MaxHIwAmXt.xyF
OdlD+7VRKjM5+HiVnJ0qaQT63J6DpSfBRhcqRV10d64yyxjD.6OMmHKLC31R
xevV6XgSzHPymf70DNg+ufSvX5U9mIbpeJI1tcGnKZhoEIUigaTZi3TOqnDq
Es6Y4ZXmr0+.aR3Bc03BUMqTpqeLue1TtqIQGceGoyA0xA
-----------end_max5_patcher-----------
</code></pre>
