### ISSUE TITLE
Hint and clue automatic setting

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#189]
It could be handy to have jcom.parameter automagically sending the name and
description to the hint and annotation attributes of the UI object it is
connected to...

e.g. it could be :
for hint : "OSC name"
for annotation : "OSC name : description"

Hmmmmm ?

see in the patch below...

----------begin_max5_patcher----------
537.3ocyUssbaBCD8Y3qPid10EANww8oz+g9VRlLxBYhx.RLRhVmlI+6UWPX
UaHAmd8AKa1cY2ydNqV+bZBbqXOUAAeBbCHI44zjDmIqgj9mSfM38jZrxEFr
gpT3JJbg2mltW6r+.iqADJWKErxOJ3g.XkN2hsO9g7hfwcBtlianNWeVxv0A
O7tFFulpcEK+fQQmNXEEkDE66tjfxVl0atEqIFvTcujRz9NCkcgwM3xM1y0t
SzkKy.20+J9jqepk5iGBA2Y87RZp8XwuH0f4bgFqYBN3VXDEY78kNIGTxTs0
3m.hcdBjZ+UiIq.Ae4svwXx7+QLom7VUXOy+ywjb52LsYnS9JVNzhiLgMvyO
RDMKawRSrZpLdXDbsERfFU08ZQUUMEbcIUQjr1dU4bzgZFmRDcbcLwFINEaN
SwAMp3TLh3r40mxW4zC+vddg+q0up5rn+y6RkLzcigmNQGBD+HCtyXCvNY01
9Fx0NwGCcRqjpLUwcoJlBJbSlqtxcc2+VwDvLn8ryk1yyckA4q7o0LFpwk0R
WDQsPNcy9NzD+3cfKsKkm5ZygsRGGwb1KMh1tF9FhCJRbPWDNOGwAMsLbkOg
HzDYeJY3j6DNJKl5covcq+n+nzgBq8eVOThNIIjsv1ZvAjX17nY7Afby.6EE
yCrxRJOddrgU1JLXqGCSLbLaHU7eGjVOCDYWs9WDRGUte+rj4gWR+A.8Bvj7
-----------end_max5_patcher-----------

 see more on the original redmine issue http://redmine.jamoma.org/issues/1374

**Comment by tap** [comment]
This makes less sense in Max 7 than before and was always a bit aspirational.  It is not essential and I don't anticipate ever working on it.
