### ISSUE TITLE
j.cue dumpout

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#19]
When you use j.cue, it outputs some message by the second outlet to describe what it does, but it seems that some informations are missing : 

When I send it "recall NameOfACue", it outputs "recall". I wish that it outputs "recall NameOfACue".
When I send it "store NameOfACue", it outputs "store". I wish that it outputs "store NameOfACue".
When I send it "store", it outputs "store". I wish that it outputs "store NameOfTheCueThatItUpdate".
When I send it "remove NameOfACue", it outputs "remove". I wish that it outputs "remove NameOfACue".
When I send it "rename NameOfACue", it outputs "rename". I wish that it outputs "rename NameOfACue".
When I send it "edit NameOfACue", it outputs "editor opened" and after "editor closed". I wish that it outputs "NameOfTheCue opened" and "NameOfTheCue closed".
When I send it "clear", it doesn't output anything. I wish that it outputs "clear".

 see more on the original redmine issue http://redmine.jamoma.org/issues/1590

**Comment by theod** [comment]
I have done something simple and available for all Modular externals based on wrapped c++ class : 
when a message with argument is sent <message inputValue>, 
the external dumps out <message inputValue outputValue>

**Comment by theod** [comment]
Note this is not taking care of the following feature :  
<edit NameOfACue> outputs <NameOfTheCue opened> then <NameOfTheCue closed>

**Comment by reno-** [comment]
ok, I agree for the last point. editor opened/closed is enough for now I can catch it for making an autosave of the cues.txt file.
and all the first requests are now working. Tx @theod
