### ISSUE TITLE
j.stencil%: @stencil attribute not defined

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#207]
1. load jcom.stencil%.maxhelp
2. watch error messages in Max window:

<pre>
jcom.stencil%: "stencil" is not a valid attribute argument
jcom.stencil%: doesn't understand "stencil"
</pre>

 see more on the original redmine issue http://redmine.jamoma.org/issues/1264

**Comment by tap** [comment]
This object is dead.  Use jit.robcross or jit.sobel instead.
