### ISSUE TITLE
update Jamoma overview

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#21]
in particular all modules should be changed from jmod.* to *.model or whatever

 see more on the original redmine issue http://redmine.jamoma.org/issues/1586

**Comment by theod** [comment]
I assign this to @jln- as he is harmonizing all the documentation. I also remember that @lossius wanted to replace this overview by severals tutorials.

**Comment by tap** [comment]
We have a new overview, which can accommodate addition of tutorials now.  Future work can occur on new tickets.
