### ISSUE TITLE
j.array= crashes when turning audio on in its maxhelp

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#219]
I get a crash with jcom.array??? when the number of channels in the incoming signal exceed 4. I can reproduce the crash when using different classes in jcom.array??? (ie. gain or filter) with the patch below.

---
Le 6 juin 2012 à 01:10, Nils Peters a écrit :

OK, I did some testing and it tuns out to be a bug in jcom.array??? but
*not* with jcom.array~.

This suggests that the bug must be related to JAG or the JAG wrapper.

 see more on the original redmine issue http://redmine.jamoma.org/issues/1165

**Comment by theod** [comment]
I still experience a crash when enabling audio into j.array=.maxhelp

Thread 40 Crashed:: com.apple.audio.IOThread.client
0   libJamomaFoundation.6.dylib   	0x0b65e264 TTEnvironment::releaseInstance(TTObjectBase**) + 84 (TTEnvironment.cpp:288)
1   libJamomaFoundation.6.dylib   	0x0b65e68c TTObjectBaseRelease(TTObjectBase**) + 60 (TTEnvironment.cpp:342)
2   libJamomaDSP.6.dylib          	0x0b6109c2 TTAudioSignalArray::setSignal(unsigned short, TTAudioSignal*) + 82 (TTAudioSignalArray.cpp:104)
3   libJamomaAudioGraph.6.dylib   	0x0b19c862 TTAudioArray::setStream(unsigned short, TTAudioSignal*) + 66 (TTAudioObject.h:117)
4   libJamomaAudioGraph.6.dylib   	0x0b19a5dd TTAudioGraphObjectBase::preprocess(TTAudioGraphPreprocessData const&) + 589 (TTAudioGraphObject.cpp:207)
5   libJamomaAudioGraph.6.dylib   	0x0b1a2b68 TTAudioGraphSource::preprocess(TTAudioGraphPreprocessData const&) + 40 (TTAudioGraphSource.h:140)
6   libJamomaAudioGraph.6.dylib   	0x0b19c78d TTAudioGraphInlet::preprocess(TTAudioGraphPreprocessData const&) + 317 (TTAudioGraphInlet.h:194)
7   libJamomaAudioGraph.6.dylib   	0x0b19a590 TTAudioGraphObjectBase::preprocess(TTAudioGraphPreprocessData const&) + 512 (TTAudioGraphObject.cpp:204)
8   libJamomaAudioGraph.6.dylib   	0x0b1a2b68 TTAudioGraphSource::preprocess(TTAudioGraphPreprocessData const&) + 40 (TTAudioGraphSource.h:140)
9   libJamomaAudioGraph.6.dylib   	0x0b19c78d TTAudioGraphInlet::preprocess(TTAudioGraphPreprocessData const&) + 317 (TTAudioGraphInlet.h:194)
10  libJamomaAudioGraph.6.dylib   	0x0b19a590 TTAudioGraphObjectBase::preprocess(TTAudioGraphPreprocessData const&) + 512 (TTAudioGraphObject.cpp:204)
11  libJamomaAudioGraph.6.dylib   	0x0b1a2b68 TTAudioGraphSource::preprocess(TTAudioGraphPreprocessData const&) + 40 (TTAudioGraphSource.h:140)
12  libJamomaAudioGraph.6.dylib   	0x0b19c78d TTAudioGraphInlet::preprocess(TTAudioGraphPreprocessData const&) + 317 (TTAudioGraphInlet.h:194)
13  libJamomaAudioGraph.6.dylib   	0x0b19a590 TTAudioGraphObjectBase::preprocess(TTAudioGraphPreprocessData const&) + 512 (TTAudioGraphObject.cpp:204)
14  libJamomaAudioGraph.6.dylib   	0x0b1a2b68 TTAudioGraphSource::preprocess(TTAudioGraphPreprocessData const&) + 40 (TTAudioGraphSource.h:140)
15  libJamomaAudioGraph.6.dylib   	0x0b19c78d TTAudioGraphInlet::preprocess(TTAudioGraphPreprocessData const&) + 317 (TTAudioGraphInlet.h:194)
16  libJamomaAudioGraph.6.dylib   	0x0b19a590 TTAudioGraphObjectBase::preprocess(TTAudioGraphPreprocessData const&) + 512 (TTAudioGraphObject.cpp:204)
17  org.jamoma.j.unpack=          	0x10bc1054 UnpackPerform64(_unpack*, object*, double**, long, double**, long, long, long, void*) + 132 (j.unpack.cpp:296)
18  com.cycling74.MaxAudioAPI     	0x09865e70 dspchain_tick + 454
19  com.cycling74.MaxAudioAPI     	0x098767c5 plugrunner_tick + 155
20  com.cycling74.MaxAudioAPI     	0x098777e8 plugrunner_process + 218
21  com.cycling74.MaxAudioAPI     	0x0989158d patchernode_process + 298
22  com.cycling74.MaxAudioAPI     	0x0988e561 mixerengine_process_fun + 83
23  com.cycling74.Max             	0x00153d58 linklist_funall_imp + 116
24  com.cycling74.Max             	0x00152f91 linklist_funall + 39
25  com.cycling74.MaxAudioAPI     	0x0988e4f1 mixerengine_process + 99
26  com.cycling74.MaxAudioAPI     	0x0988e303 mixerengine_processiovector + 816
27  com.cycling74.MaxAudioAPI     	0x09862dd0 ad_process + 269
28  com.cycling74.ad-coreaudio    	0x099441c9 adcoreaudio_callback + 181
29  com.cycling74.Max             	0x00414129 WrapperCallback::audioDeviceIOCallback(float const**, int, float**, int, int) + 65
30  com.cycling74.Max             	0x0058c38d juce::CoreAudioInternal::audioCallback(AudioBufferList const*, AudioBufferList*) + 309
31  com.cycling74.Max             	0x0058c251 juce::CoreAudioInternal::audioIOProc(unsigned long, AudioTimeStamp const*, AudioBufferList const*, AudioTimeStamp const*, AudioBufferList*, AudioTimeStamp const*, void*) +

**Comment by tap** [comment]
cannot reproduce
