### ISSUE TITLE
jcom.net.send doesn't work in TCP mode

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#223]
as stated in @jcom.net.send.maxhelp@

_not really sure what is going on here..._
_If you send some messages, they are indeed sent.  However, the mxj object will not dump them to its outlet until the connection is closed (e.g. you change the port.)_

 see more on the original redmine issue http://redmine.jamoma.org/issues/1110

**Comment by tap** [comment]
this object is quarantined and probably to be killed altogether
