### ISSUE TITLE
"A Plugtastic Instrument" example crashes when trying to build

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#225]
as reported by Alex Aliferis today.

on my machine, the crashlog looks like this

<pre>

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Codes: KERN_PROTECTION_FAILURE at 0x0000000000000008
Crashed Thread:  14

...

Thread 14 Crashed:
0   libstdc++.6.dylib             	0x9a70eb33 std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) + 23
1   JamomaFoundation.dylib        	0x178eb64a TTSymbol::getString() + 26
2   org.jamoma.jcom.plug.out      	0x1e60a3d6 PlugtasticAudioGraphDescription::ExportNode(std::string&, long&, std::vector<std::string, std::allocator<std::string> >&) + 406 (jcom.plug.out.export.mm:303)
3   org.jamoma.jcom.plug.out      	0x1e60a3d6 PlugtasticAudioGraphDescription::ExportNode(std::string&, long&, std::vector<std::string, std::allocator<std::string> >&) + 406 (jcom.plug.out.export.mm:303)
4   org.jamoma.jcom.plug.out      	0x1e60a3d6 PlugtasticAudioGraphDescription::ExportNode(std::string&, long&, std::vector<std::string, std::allocator<std::string> >&) + 406 (jcom.plug.out.export.mm:303)
5   org.jamoma.jcom.plug.out      	0x1e602d4b PlugOutDoBuildAudioUnit_Export + 1099 (stl_vector.h:752)
6   JamomaFoundation.dylib        	0x178d1e16 TTThreadCallback(void*) + 22
7   libSystem.B.dylib             	0x9438f259 _pthread_start + 345
8   libSystem.B.dylib             	0x9438f0de thread_start + 34
</pre>

 see more on the original redmine issue http://redmine.jamoma.org/issues/1104

**Comment by tap** [comment]
graph externs removed / quarantined for 1.0
