### ISSUE TITLE
jcom.hilbert???

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#241]
Create AudioGraph wrapper for the Hilbert filters.

We need to consider whether we want/need to introduce arrays of complex signals, and how we want to do inlets and outlets. In the process we should also be considering FFT stuff where the same concerns are at play.

 see more on the original redmine issue http://redmine.jamoma.org/issues/974

**Comment by lossius** [comment]
I'm updating the title to be more precise with what the current situation is:

- We have source code for an j.hilbert= external
- Integration tests reveal that the object is not loading. Max post the message "newobj: j.hilbert=: No such object"

Do this object need to be fixed or quarantined?

Assigning issue to @tap.

**Comment by tap** [comment]
We can do better than quarantine -- I suggest just deleting it altogether.
