### ISSUE TITLE
j.average= produces NaN and inf

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#243]
Steps to reproduce:

- Open jmod.average≈.maxhelp
- Start audio

It's not 100% reproduce able, but something weird seems to be going on.

Try quiting and restarting Max. Also try turning audio off, closing the patch and then open it again, and start audio a new.

Sometimes it work fine, at other times it produce NaN or inf.

If you select mode from the pop-up-menu it starts behaving properly.

 see more on the original redmine issue http://redmine.jamoma.org/issues/924

**Comment by theod** [comment]
it seems to be fixed but I need someone else to check it is ok before to close

**Comment by reno-** [comment]
it works for me too
