### ISSUE TITLE
hiding JAG messages from Max user

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#251]
In Max5, when doing an option+mouse-click on the left inlet of a JAG external, the list of  Attributes and messages appear.
Under MEssages a lot of the JAG internal messages appear, (e.g., audio.connect, calculate, getProcessingBenchmark, test,) mixed in between the 'useful' messages of that external (e.g., setLinearGain). 

Is it possible to hide all the internal messages from the user ?

 see more on the original redmine issue http://redmine.jamoma.org/issues/801

**Comment by tap** [comment]
no going to do it, it's a distraction
