### ISSUE TITLE
j.split=.maxhelp crashes

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#252]
1. open jcom.split???.maxhelp
2. turn on DSP
3. Crash!

the crashlog is the following 

<pre>
Process:         ReportCrash [359]
Path:            /System/Library/CoreServices/ReportCrash
Identifier:      ReportCrash
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [227]

Date/Time:       2011-06-17 16:39:57.164 -0700
OS Version:      Mac OS X 10.6.7 (10J869)
Report Version:  6

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Crashed Thread:  7

Application Specific Information:
abort() called
Analyzing process: MaxMSP[340], path: /Applications/Max5/MaxMSP.app/Contents/MacOS/MaxMSP; parent process: launchd[227], path: /sbin/launchd
 

Thread 0:  Dispatch queue: com.apple.main-thread
0   libSystem.B.dylib             	0x00007fff80097f8a __semwait_signal + 10
1   libSystem.B.dylib             	0x00007fff80097e19 nanosleep + 148
2   libSystem.B.dylib             	0x00007fff800e4df0 sleep + 61
3   ReportCrash                   	0x000000010000882f 0x100000000 + 34863
4   ReportCrash                   	0x0000000100001cf0 0x100000000 + 7408

Thread 1:
0   libSystem.B.dylib             	0x00007fff8006780a __getdirentries64 + 10
1   libSystem.B.dylib             	0x00007fff80067798 _readdir_unlocked$INODE64 + 79
2   libSystem.B.dylib             	0x00007fff80067730 readdir$INODE64 + 67
3   com.apple.CoreFoundation      	0x00007fff855d760b _CFBundleCopyDirectoryContentsAtPath + 1627
4   com.apple.CoreFoundation      	0x00007fff855ddafd _CFBundleCopyInfoDictionaryInDirectoryWithVersion + 1005
5   com.apple.CoreFoundation      	0x00007fff855dd70a CFBundleGetInfoDictionary + 74
6   com.apple.CoreFoundation      	0x00007fff855d5d49 _CFBundleCreate + 697
7   com.apple.CoreFoundation      	0x00007fff856582de _CFBundleCreateIfLooksLikeBundle + 14
8   com.apple.CoreFoundation      	0x00007fff856581eb _CFBundleCreateWithExecutableURLIfLooksLikeBundle + 187
9   ReportCrash                   	0x0000000100006c44 0x100000000 + 27716
10  ReportCrash                   	0x00000001000070ba 0x100000000 + 28858
11  ReportCrash                   	0x00000001000028ea 0x100000000 + 10474
12  ReportCrash                   	0x0000000100009b37 0x100000000 + 39735
13  ReportCrash                   	0x000000010000a2ac 0x100000000 + 41644
14  libSystem.B.dylib             	0x00007fff800964f6 _pthread_start + 331
15  libSystem.B.dylib             	0x00007fff800963a9 thread_start + 13

Thread 2:
0   libSystem.B.dylib             	0x00007fff8005d29a mach_msg_trap + 10
1   libSystem.B.dylib             	0x00007fff8005d90d mach_msg + 59
2   libSystem.B.dylib             	0x00007fff800a297f mach_msg_server_once + 285
3   ReportCrash                   	0x000000010000a256 0x100000000 + 41558
4   libSystem.B.dylib             	0x00007fff800964f6 _pthread_start + 331
5   libSystem.B.dylib             	0x00007fff800963a9 thread_start + 13

Thread 3:  Dispatch queue: com.apple.libdispatch-manager
0   libSystem.B.dylib             	0x00007fff8007612a kevent + 10
1   libSystem.B.dylib             	0x00007fff80077ffd _dispatch_mgr_invoke + 154
2   libSystem.B.dylib             	0x00007fff80077cd4 _dispatch_queue_invoke + 185
3   libSystem.B.dylib             	0x00007fff800777fe _dispatch_worker_thread2 + 252
4   libSystem.B.dylib             	0x00007fff80077128 _pthread_wqthread + 353
5   libSystem.B.dylib             	0x00007fff80076fc5 start_wqthread + 13

Thread 4:
0   libSystem.B.dylib             	0x00007fff80076f4a __workq_kernreturn + 10
1   libSystem.B.dylib             	0x00007fff8007735c _pthread_wqthread + 917
2   libSystem.B.dylib             	0x00007fff80076fc5 start_wqthread + 13

Thread 5:
0   libSystem.B.dylib             	0x00007fff8005d29a mach_msg_trap + 10
1   libSystem.B.dylib             	0x00007fff8005d90d mach_msg + 59
2   com.apple.CoreFoundation      	0x00007fff85615932 __CFRunLoopRun + 1698
3   com.apple.CoreFoundation      	0x00007fff85614dbf CFRunLoopRunSpecific + 575
4   com.apple.DebugSymbols        	0x00007fff837a24ac SpotlightQueryThread(void*) + 380
5   libSystem.B.dylib             	0x00007fff800964f6 _pthread_start + 331
6   libSystem.B.dylib             	0x00007fff800963a9 thread_start + 13

Thread 6:
0   libSystem.B.dylib             	0x00007fff80076f4a __workq_kernreturn + 10
1   libSystem.B.dylib             	0x00007fff8007735c _pthread_wqthread + 917
2   libSystem.B.dylib             	0x00007fff80076fc5 start_wqthread + 13

Thread 7 Crashed:
0   libSystem.B.dylib             	0x00007fff800cfe4e __semwait_signal_nocancel + 10
1   libSystem.B.dylib             	0x00007fff800cfd50 nanosleep$NOCANCEL + 129
2   libSystem.B.dylib             	0x00007fff8012c6ae usleep$NOCANCEL + 57
3   libSystem.B.dylib             	0x00007fff8014bce0 abort + 93
4   libSystem.B.dylib             	0x00007fff800636b5 free + 128
5   com.apple.CoreSymbolication   	0x00007fff81f70544 CSCppStringCache::~CSCppStringCache() + 90
6   com.apple.CoreSymbolication   	0x00007fff81f8545a TRawSymbolOwnerData<Pointer32>::~TRawSymbolOwnerData() + 284
7   com.apple.CoreSymbolication   	0x00007fff81f70208 remove_locked(__gnu_cxx::_Hashtable_iterator<std::pair<CSCppSymbolOwner const, CSCppSymbolOwnerData*>, CSCppSymbolOwner, CSCppSymbolOwnerHashFunctor, std::_Select1st<std::pair<CSCppSymbolOwner const, CSCppSymbolOwnerData*> >, CSCppSymbolOwnerEqualsFunctor, std::allocator<CSCppSymbolOwnerData*> >) + 112
8   com.apple.CoreSymbolication   	0x00007fff81f9182e clean_locked() + 212
9   com.apple.CoreSymbolication   	0x00007fff81f700f9 cleaner_thread_main(void*) + 69
10  libSystem.B.dylib             	0x00007fff800964f6 _pthread_start + 331
11  libSystem.B.dylib             	0x00007fff800963a9 thread_start + 13

Thread 7 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000003c  rbx: 0x0000000121d8fcd0  rcx: 0x0000000121d8fc88  rdx: 0x0000000000000001
  rdi: 0x0000000000000c03  rsi: 0x0000000000000000  rbp: 0x0000000121d8fcc0  rsp: 0x0000000121d8fc88
   r8: 0x0000000000000000   r9: 0x0000000000989680  r10: 0x0000000000000001  r11: 0x0000000000000246
  r12: 0x0000000000000000  r13: 0x0000000100057000  r14: 0x0000000000000000  r15: 0x00000001201321a0
  rip: 0x00007fff800cfe4e  rfl: 0x0000000000000247  cr2: 0x0000000100582880

Binary Images:
       0x100000000 -        0x10000fff7  ReportCrash ??? (???) <6D659CCB-A577-46CE-F70C-32E14CD7FA7F> /System/Library/CoreServices/ReportCrash
    0x7fff5fc00000 -     0x7fff5fc3bdef  dyld 132.1 (???) <472D950D-70F8-B810-A959-9184C2AA6C74> /usr/lib/dyld
    0x7fff8005c000 -     0x7fff8021dfff  libSystem.B.dylib 125.2.10 (compatibility 1.0.0) <9BAEB2F2-B485-6349-E1AB-637FE12EE770> /usr/lib/libSystem.B.dylib
    0x7fff802d2000 -     0x7fff8034ffef  libstdc++.6.dylib 7.9.0 (compatibility 7.0.0) <35ECA411-2C08-FD7D-11B1-1B7A04921A5C> /usr/lib/libstdc++.6.dylib
    0x7fff803e1000 -     0x7fff80669fef  com.apple.security 6.1.2 (55002) <015C9A08-3D07-9462-8E91-DB1924349621> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff8075e000 -     0x7fff8076fff7  libz.1.dylib 1.2.3 (compatibility 1.0.0) <FB5EE53A-0534-0FFA-B2ED-486609433717> /usr/lib/libz.1.dylib
    0x7fff8097e000 -     0x7fff809b9fff  com.apple.AE 496.4 (496.4) <CBEDB6A1-FD85-F842-4EB8-CC289FAE0F24> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff811cc000 -     0x7fff8122cfe7  com.apple.framework.IOKit 2.0 (???) <D107CB8A-5182-3AC4-35D0-07068A695C05> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff81f66000 -     0x7fff81fe9fef  com.apple.CoreSymbolication 2.1 (46) <9F1EEDC7-4779-04E4-8C3C-38202CF1227F> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff8205f000 -     0x7fff82176fef  libxml2.2.dylib 10.3.0 (compatibility 10.0.0) <1B27AFDD-DF87-2009-170E-C129E1572E8B> /usr/lib/libxml2.2.dylib
    0x7fff82f40000 -     0x7fff82f68fff  com.apple.DictionaryServices 1.1.2 (1.1.2) <E9269069-93FA-2B71-F9BA-FDDD23C4A65E> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff834ac000 -     0x7fff8353cfff  com.apple.SearchKit 1.3.0 (1.3.0) <4175DC31-1506-228A-08FD-C704AC9DF642> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff835ee000 -     0x7fff835f4ff7  com.apple.DiskArbitration 2.3 (2.3) <857F6E43-1EF4-7D53-351B-10DE0A8F992A> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff83601000 -     0x7fff8364dfff  libauto.dylib ??? (???) <F7221B46-DC4F-3153-CE61-7F52C8C293CF> /usr/lib/libauto.dylib
    0x7fff8379d000 -     0x7fff837dbfef  com.apple.DebugSymbols 1.1 (70) <C3D11461-E118-09DB-D9D7-8972B3FD160F> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff837de000 -     0x7fff8383bfe7  com.apple.Symbolication 1.2 (72) <BED6B51F-7EAD-EA8C-0540-CE7BF12785F5> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fff83fc4000 -     0x7fff83fc8ff7  libmathCommon.A.dylib 315.0.0 (compatibility 1.0.0) <95718673-FEEE-B6ED-B127-BCDBDB60D4E5> /usr/lib/system/libmathCommon.A.dylib
    0x7fff84378000 -     0x7fff84386ff7  libkxld.dylib ??? (???) <4016E9E6-0645-5384-A697-2775B5228113> /usr/lib/system/libkxld.dylib
    0x7fff84575000 -     0x7fff845bfff7  com.apple.Metadata 10.6.3 (507.15) <5170FCE0-ED6C-2E3E-AB28-1DDE3F628FC5> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff84cab000 -     0x7fff84f2efe7  com.apple.Foundation 6.6.6 (751.53) <476E617B-B59B-53DE-991D-98C1993BCBCE> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff85265000 -     0x7fff8527bfef  libbsm.0.dylib ??? (???) <42D3023A-A1F7-4121-6417-FCC6B51B3E90> /usr/lib/libbsm.0.dylib
    0x7fff85542000 -     0x7fff85583fff  com.apple.SystemConfiguration 1.10.5 (1.10.2) <FB39F09C-57BB-D8CC-348D-93E00C602F7D> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff855c9000 -     0x7fff85740fe7  com.apple.CoreFoundation 6.6.4 (550.42) <770C572A-CF70-168F-F43C-242B9114FCB5> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff85741000 -     0x7fff857fafff  libsqlite3.dylib 9.6.0 (compatibility 9.0.0) <2C5ED312-E646-9ADE-73A9-6199A2A43150> /usr/lib/libsqlite3.dylib
    0x7fff86518000 -     0x7fff86543ff7  libxslt.1.dylib 3.24.0 (compatibility 3.0.0) <87A0B228-B24A-C426-C3FB-B40D7258DD49> /usr/lib/libxslt.1.dylib
    0x7fff865a5000 -     0x7fff865b0fff  com.apple.CrashReporterSupport 10.6.7 (258) <BB0B9A08-6CEC-0500-5BD1-C18E1465E406> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff865b1000 -     0x7fff86683fe7  com.apple.CFNetwork 454.11.12 (454.11.12) <B1C9008A-4A5D-609D-5D10-C93DAD6FFB4C> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff86935000 -     0x7fff86af3fff  libicucore.A.dylib 40.0.0 (compatibility 1.0.0) <2C6ECACF-CD56-1714-6F63-CB6F5EE7A1E2> /usr/lib/libicucore.A.dylib
    0x7fff86bb8000 -     0x7fff86c6efff  libobjc.A.dylib 227.0.0 (compatibility 1.0.0) <F206BE6D-8777-AE6C-B367-7BEA76C14241> /usr/lib/libobjc.A.dylib
    0x7fff86c6f000 -     0x7fff86d2cfff  com.apple.CoreServices.OSServices 359 (359) <8F509D8D-4C94-9A1C-3A87-5B775D9F6075> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff86d2e000 -     0x7fff87062fff  com.apple.CoreServices.CarbonCore 861.34 (861.34) <B5680539-CB31-6C6D-C0AD-606D4D46E7F5> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff87065000 -     0x7fff87065ff7  com.apple.CoreServices 44 (44) <DC7400FB-851E-7B8A-5BF6-6F50094302FB> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff87db4000 -     0x7fff87e54fff  com.apple.LaunchServices 362.2 (362.2) <A8EDC37C-1D40-5ED0-49BE-90EF110A6B3A> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff87fb6000 -     0x7fff87fc5fff  com.apple.NetFS 3.2.2 (3.2.2) <7CCBD70E-BF31-A7A7-DB98-230687773145> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff88803000 -     0x7fff88809ff7  com.apple.CommerceCore 1.0 (9) <4C66D962-91B5-F25C-A6FF-DFD5F924A0DD> /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Frameworks/CommerceCore.framework/Versions/A/CommerceCore
    0x7fffffe00000 -     0x7fffffe01fff  libSystem.B.dylib ??? (???) <9BAEB2F2-B485-6349-E1AB-637FE12EE770> /usr/lib/libSystem.B.dylib

 </pre>

 see more on the original redmine issue http://redmine.jamoma.org/issues/784

**Comment by theod** [comment]
not any more
