### ISSUE TITLE
j.soundfile.player= crashes sometimes with seek

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#264]
sometimes, more often when sent multiple times, the seek message (e.g. seek 1000) crashes jcom.soundfile.player???.
see below. Meybe we need to defer something in the code to avoid that?  

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000059b362f4
Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   ???                           	0x59b362f4 0 + 1504928500
1   SoundfileLib.ttdylib          	0x1791618a FLAC__stream_decoder_seek_absolute + 2362
2   SoundfileLib.ttdylib          	0x1789c604 flac_seek + 84 (flac.c:1286)
3   SoundfileLib.ttdylib          	0x178c3a0d sf_seek + 829 (sndfile.c:1356)
4   SoundfileLib.ttdylib          	0x17889cb3 TTSoundfilePlayer::setSeek(TTValue const&) + 179 (TTSoundfilePlayer.cpp:103)
5   org.jamoma.JamomaFoundation   	0x02b5b673 TTObject::setAttributeValue(TTSymbol*, TTValue&) + 515
6   ...moma.jcom.soundfile.player???	0x00d5ef76 MaxAudioGraphWrappedClass_attrSet(_wrappedInstance*, object*, long, atom*) + 388 (maxAudioGraph.cpp:221)
7   com.cycling74.MaxMSP          	0x000bad87 object_attr_setvalueof + 199
8   com.cycling74.MaxMSP          	0x0001cc20 typedmess_fun + 782
9   com.cycling74.MaxMSP          	0x00064497 outlet_anything + 727
10  com.cycling74.MaxMSP          	0x0001cc20 typedmess_fun + 782
11  com.cycling74.MaxMSP          	0x0001d151 typedmess + 83
12  com.cycling74.MaxMSP          	0x0001d7bd aeval + 893
13  com.cycling74.MaxMSP          	0x00008b5c atombuf_eval + 152
14  com.cycling74.MaxAPI          	0x022d2f43 atombuf_eval + 60
15  com.cycling74.message         	0x198d90ad jmessage_atombuf_eval + 429
16  com.cycling74.message         	0x198d9409 jmessage_bang + 129
17  com.cycling74.message         	0x198d94ca jmessage_mousedown + 182
18  com.cycling74.MaxMSP          	0x000bab4f object_method + 901
19  com.cycling74.MaxMSP          	0x0010bcfe BoxComponent::sendMouseMessage(juce::MouseEvent const&, symbol*, double, double) + 414
20  com.cycling74.MaxMSP          	0x0010efc0 BoxComponent::mouseDown(juce::MouseEvent const&) + 770
21  com.cycling74.MaxMSP          	0x002f76fa juce::Component::internalMouseDown(int, int) + 802
22  com.cycling74.MaxMSP          	0x0038f394 juce::ComponentPeer::handleMouseDown(int, int, long long) + 436
23  com.cycling74.MaxMSP          	0x002d782e juce::HIViewComponentPeer::handleMouseEvent(OpaqueEventHandlerCallRef*, OpaqueEventRef*) + 742
24  com.cycling74.MaxMSP          	0x002d8042 juce::HIViewComponentPeer::handleWindowEventForPeer(OpaqueEventHandlerCallRef*, OpaqueEventRef*) + 278
25  com.cycling74.MaxMSP          	0x002d80ef juce::HIViewComponentPeer::handleWindowEvent(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*) + 65
26  com.apple.HIToolbox           	0x93052f2f DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1567
27  com.apple.HIToolbox           	0x930521f6 SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 411
28  com.apple.HIToolbox           	0x930749bb SendEventToEventTarget + 52
29  com.apple.HIToolbox           	0x930864db ToolboxEventDispatcherHandler(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*) + 1257
30  com.apple.HIToolbox           	0x93053380 DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 2672
31  com.apple.HIToolbox           	0x930521f6 SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 411
32  com.apple.HIToolbox           	0x930749bb SendEventToEventTarget + 52
33  com.cycling74.MaxMSP          	0x002d1102 juce::juce_dispatchNextMessageOnSystemQueue(bool, bool) + 630
34  com.cycling74.MaxMSP          	0x002dac8b juce::MessageManager::dispatchNextMessage(bool, bool*, bool) + 79
35  com.cycling74.MaxMSP          	0x002dad4a juce::MessageManager::runDispatchLoop() + 42
36  com.cycling74.MaxMSP          	0x002d96a5 juce::JUCEApplication::main(juce::String&, juce::JUCEApplication*) + 605
37  com.cycling74.MaxMSP          	0x002d977f juce::JUCEApplication::main(int, char**, juce::JUCEApplication*) + 125
38  com.cycling74.MaxMSP          	0x001e3816 main + 76
39  com.cycling74.MaxMSP          	0x0000617e _start + 216
40  com.cycling74.MaxMSP          	0x000060a5 start + 41

 see more on the original redmine issue http://redmine.jamoma.org/issues/559

**Comment by theod** [comment]
it seems to be fixed so I close the issue
