### ISSUE TITLE
jcom.split??? crash when groups definition exceeds number of audiochannels

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#269]
for instace, if incoming multicable has 5 channels and groups are set to @groups 2 10, we get a crash:

Thread 7 Crashed:
0   org.jamoma.JamomaDSP          	0x12c29c5d TTAudioSignal::copySubset(TTAudioSignal const&, TTAudioSignal&, unsigned short, unsigned short) + 109
1   org.jamoma.jcom.split???        	0x01a71abe TTMulticoreSplit::processAudio(TTAudioSignalArray*, TTAudioSignalArray*) + 268 (jcom.split.cpp:56)
2   org.jamoma.JamomaDSP          	0x12c283f0 TTAudioObject::process(TTAudioSignalArray*, TTAudioSignalArray*) + 64
3   org.jamoma.JamomaMulticore    	0x16e3a92b TTMulticoreObject::process(TTAudioSignal*&, unsigned short) + 971
4   org.jamoma.JamomaMulticore    	0x16e3c272 TTMulticoreInlet::process() + 162
5   org.jamoma.JamomaMulticore    	0x16e3a788 TTMulticoreObject::process(TTAudioSignal*&, unsigned short) + 552
6   org.jamoma.jcom.unpack???       	0x1a40398e OutPerform(int*) + 104 (TTMulticoreObject.h:130)
7   com.cycling74.MaxAudioAPI     	0x12c57d53 dspchain_tick + 90
8   com.cycling74.MaxAudioAPI     	0x12c56783 ad_process + 470
9   com.cycling74.ad_coreaudio    	0x177915f3 coreaudio_twodevice_ioproc + 537
10  ....audio_hijack_server.hermes	0x00defb46 AudioDeviceIOCallback + 82
11  com.apple.audio.CoreAudio     	0x977465b4 HP_IOProc::Call(AudioTimeStamp const&, AudioTimeStamp const&, AudioBufferList const*, AudioTimeStamp const&, AudioBufferList*) + 374
12  com.apple.audio.CoreAudio     	0x9774631a IOA_Device::CallIOProcs(AudioTimeStamp const&, AudioTimeStamp const&, AudioTimeStamp const&) + 370
13  com.apple.audio.CoreAudio     	0x97746116 HP_IOThread::PerformIO(AudioTimeStamp const&, double) + 620
14  com.apple.audio.CoreAudio     	0x977434fa HP_IOThread::WorkLoop() + 2506
15  com.apple.audio.CoreAudio     	0x97742b2b HP_IOThread::ThreadEntry(HP_IOThread*) + 17
16  com.apple.audio.CoreAudio     	0x97742a42 CAPThread::Entry(CAPThread*) + 140
17  libSystem.B.dylib             	0x910d7fbd _pthread_start + 345
18  libSystem.B.dylib             	0x910d7e42 thread_start + 34

 see more on the original redmine issue http://redmine.jamoma.org/issues/448

**Comment by tap** [comment]
this one has been fixed at some point and is no longer reproducible.
