### ISSUE TITLE
investigate using externals refpages for j~ and j≈ 

### ISSUE THREAD

**Issue by bltzr** [jamoma/JamomaMax#282]
as mentioned in https://github.com/jamoma/JamomaMax/issues/281 it would be great if externals implemented with j~ and j≈ could gather information from the corresponding externals, notably for attribute autocompletion support when creating the objects in Max

**Comment by tap** [comment]
We discussed these objects at the Florida workshop.  There are many downsides to them including the fact that Max cannot provide autocompletion for them or many other expected conveniences.

I think we should keep the objects as they are useful in the cases where a proper wrapper has not been provided, but these objects will never provide the superior experience of a real object.
