### ISSUE TITLE
externals.loading.test cause a number of warnings

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#44]
Hi Theo,

If I open Modular/Tests/integration/externals.loading.test.maxpat with CMD + SHIFT down (in order to prevent loadbang from firing), I see a few warnings in the Max window:

<pre>
jcom.return: needs a name as first argument
jcom.parameter: "view/freeze" is not a valid attribute argument
Jitter initialized
jcom.out: Jamoma cannot registers multiple object with the same OSC identifier (out).  Using out.1 instead.
jcom.in: Jamoma cannot registers multiple object with the same OSC identifier (in).  Using in.1 instead.
</pre>

I suppose some of the objects need arguments to avoid these warnings, right? Am I right that the node-related objects really need an additional argument (name of the node), and that jcom.out and jcom.in are also nodes? If so I'll add arguments as required to them. However it might be ab idea that we do a merge of master into this branch first to make sure that we do not end up with any conflicts.

 see more on the original redmine issue http://redmine.jamoma.org/issues/1552

**Comment by lossius** [comment]
This is no longer the case.
