### ISSUE TITLE
autofollow for jcom.cue

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#47]
the idea is to have a flag in the cuelist file for the autofollow function

- autofollow 2000 for example

but it will not be easy to have it. I can add an other flag but I feel there is a more general way to handle it. I'm also pretty convince this kind of information should not be stored in the cue itself but as to part of a scenario structure which could handle many cues from many cuemanager...

 see more on the original redmine issue http://redmine.jamoma.org/issues/1540

**Comment by reno-** [comment]
j.cue is a cue bin, where cues are not ordered.
We need a j.cuesheet to make sequences, autofollow, repeat and other functionality.
