### ISSUE TITLE
The @type none should be better documented for parameter/message/return

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#516]
We should incorporate topics from [this discussion](http://jamoma-forums-mailing-lists.3076123.n2.nabble.com/service-data-generic-tp7580556.html;cid=1390859518656-872) into the help files.

**Comment by jln-** [comment]
Rather than overcrowding the maxhelp, I added a vignette on this topic. See: https://github.com/jamoma/JamomaMax/commit/82701e70e9cc15d45e2221e64df96affd06bda40

@lossius Closing this issue. Just let me know if you think we should add further info on this topic
