### ISSUE TITLE
Create a table to document the various datatypes

### ISSUE THREAD

**Issue by nwolek** [jamoma/JamomaMax#531]
This should be clearly explained in the web and Max tutorials. 

Datatypes include:
* none
* generic
* boolean
* _integer_
* _decimal_
* string
* _array_

Those in italics can be used with dataspace and ramp.

The [proposal/decision in Bergen](https://github.com/jamoma/Jamoma/wiki/Workshop-BEK-March-2014#wiki-externals) was to eliminate the different decimalArray and integerArray datatypes going forward.

**Comment by lossius** [comment]
This has now been thoroughly documented in the help file for j.parameter. The information should be in the ref page for j.parameter as well.

In addition similar information should be present in the help and ref files for j.message and j.return. In these help files we also need to document the type none that is not used with j.parameter.

One question to consider here is how to make this DRY. We could make a separate patch embedded as a bpatcher in all three help files, but I'm not necessarily convinced that this will be the best way forward. I'll contemplate this as I move forward with revising help files for j.message and j.return once the help file for j.parameter is complete.

**Comment by lossius** [comment]
I'm considering this issue as resolved.
