### ISSUE TITLE
export modules documentation as yaml

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#57]
Since we have a script to compile yaml reference pages as xml maybe we could it be useful to unify the docs and have the module ref page as yaml too ?

We also need a yaml2html converter so hopefully, module pages as yaml could also benefit from this.

 see more on the original redmine issue http://redmine.jamoma.org/issues/1526

**Comment by jln-** [comment]
This duplicates https://github.com/jamoma/JamomaMax/issues/713 Closing.
