### ISSUE TITLE
j.pack- crash

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#655]
Steps to reproduce:

1. Open Integrations/Max/Jamoma/help/j.dataspace-.maxhelp
2. Send a value to the left or right j.pack- object that is connectedf to j.dataspace-

This leads to the following crash:

https://gist.github.com/lossius/20ba76fe12c8dc3d40e5

**Comment by tap** [comment]
graph externs removed / quarantined for 1.0
