### ISSUE TITLE
check if externals dependancies have 64 bits support

### ISSUE THREAD

**Issue by reno-** [jamoma/JamomaMax#686]
foreground : cv.jit.ravg
motiongram : xray.jit.mean
slitscan : xray.jit.timecube

**Comment by jln-** [comment]
Just gave it a check and cv.jit are now available as 64 bits.

xray.jit.mean used by motiongram and xray.jit.timecube used by slitscan are only available as 64 bits (similarity usese no 3d party external as it seems).

Could these 2 above be done in gen, maybe ? @matcham @reno- ?

**Comment by matcham** [comment]
...I don't think so.
even a simple cv.jit.sum cannot be done in jit.gen AFAIK.

**Comment by jln-** [comment]
It was my impression also but only gave a quick look at gen ref. Too bad.

In the mean time, I added a warning in maxhelps that these models are 32 bits only.

**Comment by jln-** [comment]
Since I checked, I consider this issue closed. We'll need to discuss whether we want to maintain patches relying on 32 bits only externals
