### ISSUE TITLE
j.cue @relative 1 : recall is broken

### ISSUE THREAD

**Issue by matcham** [jamoma/JamomaMax#747]
j.cue @relative 1 : can create new cue, but recall function is broken (values are not sent to parameters)

<pre><code>
----------begin_max5_patcher----------
920.3oc6XszbaBCD9r8uBFNS8f3M8TZO0oG5z6c5jQ.abTJHw.BW2lI+2qd.
FriwwwCjLMSNDARrQ6te5a2Uque4ByD1Vn1z3iF+vXwh6WtXgZI4BKZmuvr.
uMMGWqDyLkUT.Ttok9abXKWstmXnDWgKL1fya.CRsAkwMpfTbdNj0IOsofPy
AtZyPsKVh4o2RnquVHMWaLtdqrsLbb8kObsQpGhQie19+PxTpkkb2G7617aX
TNEW.pu7oJBNefZYM7N8ZOP9ZxeUx6fVEFGhB859V05DkrqrkK7vxkxAqyDk
Jf5Z7Z3QnTbbb2ZZ6g+mRP6wll67s8.ImwAoPzJeKiHEF4aKGQQGGh7dtPD5
HPDx4hvBoymzv4L53ttk9OhfXsy7SXUYP0Pi4njmdFX21mrNkkypz6s8pXWq
8FGxhFk4gjHof.50M1aVqYzyd+GbDfN5QvWf7M.mjhM9FHhZ9LKeWnh1+OPY
AVCFFpoJVCMCTpCEI4BcNnHjD3P00.EmjCCo+Rja+MGEGXGI2ba4fafcXjmR
WwQ1twC4mCnJt8.yFn57gl0Tl.0yIo+5PB2M3T3TjvA1+iT4H9fRySXfrNul
AgR3Sd.cK2yO5TQzH2WwPZwFmHBMGywkgwhn4DLc8HXvIx7ihBT9sNzSmVyw
dDPv9oAgSEArO.4Lg.D7ag88HVycq1YMF3uu60qxfavM4bg11cplSnPpHllO
zxNdhyKFh8cUObiUUWcONFG+b4YuDvXAKCxMmETITWN08T7tnWQL4kpbp6TV
NUeGkIrZp66US+OrZ5KE20YJ4t9nIl6568N48MA4srhwYRt6tyvuhKXE3U0b
nbdY3nojg6L0Ym8dmg+VpYGHaF5xQmV00Q0wyHM43G9Z1jyXW9LUvcupBxwb
xFv.MwWC0OPgH9wpG1mr+GuvK8hnmWnPns3KncZdB.0wnXBvddZlVmayO3j8
RilAZlRQp13N32WUYpx02GlpYMUocdaaiWF8laFTyITAkST9oWFYCvCD5VRV
FPGl1qfjUxDUZZsATruhVEq67KT042AyraWTKobVuQPpk4UUH2wO8OWmSFY+
jdmW3yy6hToThTm6AAcuOCVu2TbzLcli72BZl.SjmJ9QilpIy.bJi+lI62Kp
mLHeeNrd6yv5iuPxfNKBtrTT5utcKUVhHs5c5L3AVpoDJq+9ilUvFRm7QpUv
UhDjbQ1wlJc5ssQAlKk54gk+CD3u7CH
-----------end_max5_patcher-----------
</code></pre>

**Comment by jln-** [comment]
test patch provided by Mathieu and j.cue maxhelp both seems ok.

I let Mathieu testing on his side and closing the issue if ok for him as well.

**Comment by matcham** [comment]
Hi
so now, if I want to create cues containing only relative addresses, the solution is using j.model presets instead of j.cue, right ?
the way @relative 1 works now is just an easy way to set the @address attribute, right ?
(but then, should this still be named @relative ?...)
and does this quite simple namespace / address selection trick really deserves an attribute ? ...
I have the feeling that the way it works now is more confusing than helpful : we now have 2 difference messages (address + relative) that both set the address...
what should happen if I send a "address /toto" message when @relative 1 ?

actually, there's a problem in the j.cue.maxhelp patch : ("scope" tab ) :
- enable relative mode (clicking attrui)
---> j.cue @address attribute is now set to /Scope
- disable relative mode
---->  j.cue @address attribute is STILL set to /Scope

===> when disabling @relative should set address to "/"
(or should it return to previous address selected before @relative has been enabled ?

should @address attribute be disabled when @relative is enabled ?
...

**Comment by bltzr** [comment]
I don’t everything from what you explain because I’m not familiar with the way j.cue works in relative mode, but I definitely think it should be able to do it
presets are something else and, for example, they don’t allow ramps…

hasn’t that been broken when flattening the cue format ?=

**Comment by theod** [comment]
this trouble is typically relative to the choice we made to have everything as text with absolute address.
this could be fixed but as I'm working on a new state management based on dict I'm wonder if I should spend time on this ? is this issue have to be in high priority ?

**Comment by theod** [comment]
it seems the @relative attribute has been removed so I closed the issue
