### ISSUE TITLE
create a modular-only-max-packages of Jamoma

### ISSUE THREAD

**Issue by reno-** [jamoma/JamomaMax#759]
Give the possibility to download and install smaller, more specific package, with only modular part of Jamoma. That would be more relevant to certain kinds of users.

- keep the current package/distro the way it is, and the way it is done
- when making a release, after the package is done, run a script that will copy it, and remove the externals, components, help patchers,dylib not relevant to Modular.

**Comment by reno-** [comment]
Here is the list of the externals concerned. That might be the first externals needed for a Jamoma4Pd release.

The order reflects the priority.

j.loader
j.model
j.init
j.parameter
j.send
j.receive
j.remote
j.minuit
j.osc
j.namespace
j.cue
j.view
j.map
j.return
j.message
j.message_array
j.parameter_array
j.return_array
j.node
(j.in)
j.out
j.modular
j.ui

**Comment by avilleret** [comment]
hello, 

I can't find j.minuit, does it still exist ?
btw, the first 6 objects of the list are implemented in Pd 
but need (a lot of) debugging

**Comment by reno-** [comment]
Yeah !! Greetings for these first externals !!
Please tell me when I can make a build and feedbacks if it helps.

About j?minuit, it doesn’t exists (neither j.osc and j.midi).  All protocols implementations are into j.modular external.
But the plan is to split j.modular into several objects. One for each protocole. 

cheers !!

renaud

**Comment by jcelerier** [comment]
Note : with cmake it is possible to make different packages with the required externals.

If somebody wants to do this (after that I have merged the changes induced by boost removal and fixed j~ / j.vimic~, hopefully by the end of the week), it is possible to do by adding to the end of the CMakeLists.txt of each concerned external : 

    install(TARGETS ${PROJECT_NAME}
               DESTINATION "${JAMOMAMAX_MODULAR_INSTALL_FOLDER}/Jamoma/externals"
               COMPONENT JamomaMaxModularOnly) #for instance 

And adding to  https://github.com/jamoma/Jamoma/blob/dev/CMakeLists.txt the lines : 

    set(JAMOMAMAX_INSTALL_FOLDER "JamomaMax")
    install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/Implementations/Max/Jamoma"
              DESTINATION ${JAMOMAMAX_MODULAR_INSTALL_FOLDER}
              COMPONENT JamomaMax)

On OS X this will create a .dmg (when building the target Package - for instance by doing `make package`) which will contain : 
* A folder JamomaMax with the full-blown package
* A folder JamomaMaxModularOnly with only the concerned externals.
