### ISSUE TITLE
max4live crashes when trying to load an xml preset file for a Jamoma module in a frozen live device

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#76]
This happens consistently only in frozen max4live devices, although I've experienced crashes in other situations when reading\writing the preset files in m4live.

the crash log points to: jcom_core_getfilepath function in Jamoma core. 

Btw. the is a TODO annotation in the source code:
// TODO: remove this function once we've completed the transition to Max5, as path_topathname() is fixed for Max5

I've attached a crash log

 see more on the original redmine issue http://redmine.jamoma.org/issues/1505

**Comment by reno-** [comment]
Presets are now in text, and no more in xml…
