### ISSUE TITLE
j.dbap: crash on load on Mac OSX 10.8.5

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaMax#768]
a strange crash occurs when loading j.dbap on a MacOSX 10.8.5.
it seems something is missing on the system (symbol ___exp10 inside /usr/lib/libSystem.B.dylib) but I don't know what to do …

the strange thing is that there are other people with the same OSX, Max and Jamoma version who doesn't encounter such a crash ...
does someone have any clue about this ?
could it be due to the fact the release have been built on a more recent system ?

Process:         Max [33628]
Path:            /Applications/Max 6.1/Max.app/Contents/MacOS/Max
Identifier:      com.cycling74.Max
Version:         6.1.3 [c65b953] (6.1.3)
Code Type:       X86 (Native)
Parent Process:  launchd [144]
User ID:         503

Date/Time:       2014-12-04 11:20:48.462 +0100
OS Version:      Mac OS X 10.8.5 (12F45)
Report Version:  10

Interval Since Last Report:          5963751 sec
Crashes Since Last Report:           1007
Per-App Interval Since Last Report:  1057773 sec
Per-App Crashes Since Last Report:   9
Anonymous UUID:                      F9B05A94-D688-84FD-ADE2-15B29BA9C011

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Dyld Error Message:
  Symbol not found: ___exp10
  Referenced from: /Applications/Max 6.1/*/j.dbap
  Expected in: /usr/lib/libSystem.B.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dyld                          	0x8fe8f0b5 dyld_fatal_error + 1
1   dyld                          	0x8fe9201b dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 150
2   libdyld.dylib                 	0x92a6076c dyld_stub_binder_ + 20
3   j.dbap                        	0x0f7dd3e2 dbap_new(symbol*, long, atom*) + 914
4   com.cycling74.Max             	0x000205e6 typedmess_fun + 70
5   com.cycling74.Max             	0x000cb45e object_new_typed_flags + 399
6   com.cycling74.Max             	0x000cb498 object_new_typed + 46
7   com.cycling74.Max             	0x0000e7fd auxtable_search + 128
8   com.cycling74.Max             	0x000100b8 newload_internal + 102
9   com.cycling74.Max             	0x000104c0 newload + 47

**Comment by lossius** [comment]
I'd suggest testing again using the Jamoma packages generated from the automated build that @avilleret  has set up. As this is where future installers will come from, it's most important that they work. And if they don't I'd suggest that we just start stating that Jamoma requires 10.10 or newer. Simple as that...   :-)

In particular if optimisations (or lack thereof) affects the performance of the visualisation, I consider it more important to keep it speedy.

**Comment by theod** [comment]
it seems to fixed isn't it ?
