### ISSUE TITLE
what is j.snapshot ?

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#769]
`j.snapshot.cpp` includes `Jamoma.h` which I can't find in the repository regardless of the case.
I also note there is no `j.snapshot.yml` in that folder, so I guess it's not build with other externals

is it still used ? or should it be moved to the `source_quantined` folder ?

**Comment by lossius** [comment]
Closing this issue. Reimplementing the hipnoscope should be added as a separate issue.
