### ISSUE TITLE
crash when parameter_array are updated via network messages and remote_array are binding on them

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaMax#772]
This is an old trouble encountered by @bltzr. I setup an issue for it too keep all discussions we already had somewhere.

**Comment by theod** [comment]
@bltzr : can we close this issue ?

**Comment by bltzr** [comment]
I need to test that a bit more…

I’ll try to do that this week

**Comment by theod** [comment]
@bltzr : did made enough tests ? :-)

**Comment by theod** [comment]
I suppose it is ok. please reopen if it is not the case.
