### ISSUE TITLE
renaming j.parameter_array using 'address' message crashes Max

### ISSUE THREAD

**Issue by jln-** [jamoma/JamomaMax#773]
Following https://github.com/jamoma/JamomaMax/commit/d739a102c2868fb1830b486216c4627b5684ad73 (i guess), using 'address' message with j.parameter_array is broken.

Assuming an array 'foo.[6]', sending to j.parameter_array 'foo.[n]' will work as expected.

However, renaming the address using the address message does not work. ie

- 'address bar.[10]' will create nodes foo.1 to foo.6 and nodes bar.7 to bar.10.

- 'address bar.[2]' will crash Max.

See the attached demo patch and crash Log below.

CrashLog: https://gist.github.com/jln-/d621f6b59ec87d8d991d

<pre><code>
----------begin_max5_patcher----------
533.3ocyVFsaaBCEF9Z3ovxWSPfgfSp5dB1E6AHJpxANqwQfAYaZSTUe2GXC
aj0FBpYr1KvHe3f8u+3+XyKtN3ckGAEFcGZCxw4EWGGSn1.Nc8cvErio4LkI
MbZYQAHzXO6yzvQsI98eC8LOOGkJYp89998ITwzo64hGePBoZ6DEsJvOvCEl
PZuQr8HMsnscuDOyLlk6Nrf1OPh5BtHGzFYD1EToOkClbGjVYstOufdUHAUi
pYZdoXnRnTqRhauEz0f119Ru551138OiK.SCHQYFnP+rrzeS3hjsHlHCsiI8
2PWDFrcBPKHYBPa47Bs0VkPuYnU.JE6Q3MPikk0L2JKYHigEBMZfWZskJj2m
JwuKUHSjJ8zyFRepBrJ.i+8bcAfQngCz3b4x9w2ut6IxHj3ki4cVcadmYvEX
pVljKX00MAIeZl.irrBcVKZL3JYB3JldcbQ9zvk8KJM9+ylLiu4auZra9tlN
FwhlMh8AV6B34FM8lk9A+JljU.ZP9.SJYmrllkSfAj0FFDFSFCBg2DDhtHD7
5tNCFFAfy4h+9OYLqh13mSHUYsLseH6NX.8mkQyAzZtvXHGjS3Y4rmmkAhgG
VlwUrc4P1k2DbppI4KkZHeoTSzLpFqMhUU8DHUcCoQHMkTGJkscodltbgsqY
DwR3Ide9lxWLS1T7napbpkVa9wU1icvEM+9mTTyM451Nyu59KLsfllF
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
this is fixed now
