### ISSUE TITLE
j.parameter - which initial value for @type string

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaMax#774]
[j.parameter foo @type integer]  automatically outputs 0 at initialisation time.

but
[j.parameter foo @type string]  automatically outputs "" (which is converted in bang) at initialisation time.

what should be the correct behavior ? outputing "none" ? or nothing (but this is not consistent with the other types …)

**Comment by reno-** [comment]
Maybe it's a stupid question, but why are we outputting something at instantiation?

If wa want an output, we must use default or preset, isn't it?

**Comment by theod** [comment]
No it is not stupid but I prefer to let @lossius to answer to this

**Comment by bltzr** [comment]
I tend to agree with @reno-  - what does @thorangutang think about this ?

**Comment by jln-** [comment]
I also agree with Reno.










On mardi, janv. 27, 2015 at 3:44 PM, Pascal Baltazar <notifications@github.com>, wrote:
I tend to agree with @reno- - what does @thorangutang think about this ?

**Comment by lossius** [comment]
I' m also very unsure whether there is any point in outputting at initialisqtion, and suggest we discuss this at the comming BOD in order to reach a well-degined sequence of initialisqtion steps in models with respect to parameter values and default values as well as model default presets and possibly initialisation cues.

**Comment by theod** [comment]
sorry, as I'm reading what I wrote at the beginning, it is not about what it is outputted but about the very initial value.

for integer it is 0 but for string it is an empty string ("" which becomes a bang in max).

I can't remember why I post this actually so maybe this should be closed.
but I agree we should review the initialization steps at the next Bod.
