### ISSUE TITLE
j.cue 'optimize' function broken

### ISSUE THREAD

**Issue by matcham** [jamoma/JamomaMax#776]
'optimize' message to j.cue doesn't work at all. (do not removes any line in cues).
to test : j.cue.maxhelp --> "optimize cues" tab

**Comment by theod** [comment]
this trouble is typically relative to the choice we made to have everything as text with absolute address.
this could be fixed but as I'm working on a new state management based on dict I'm wonder if I should spend time on this ? is this issue have to be in high priority ?

**Comment by theod** [comment]
it is fixed on Core dev branch

**Comment by reno-** [comment]
I just tested  j.cue.maxhelp --> "optimize cues" tab and this is now working
