### ISSUE TITLE
j.dbap : please don't clip num_sources & num_destinations to 128 !

### ISSUE THREAD

**Issue by matcham** [jamoma/JamomaMax#778]
please raise up current limitation to the max number of sources & destinations in j.dbap !
(if there must be a limitation... please set it to at least 1024...)

thanks !

**Comment by theod** [comment]
I don't see any reason to not raise this limitation up but I add @lossius and @jln- to the discussion in case they have something to say

**Comment by theod** [comment]
but there is a comment in the code on top of the limitation : 
// This seems to be the current restrictions of matrix~

but maybe we don't care about this Max external limitation ?

**Comment by theod** [comment]
and there is also other limitations about weight : 
const long MAX_NUM_WEIGHTED_SOURCES = 64;
const long MAX_NUM_WEIGHTED_DESTINATIONS = 32;

those current limitation implies the creation of an 2D array of 64x32=2048 weights.
should we also raise those limitations up too ?

**Comment by matcham** [comment]
// This seems to be the current restrictions of matrix~
as j.dbap can be used without matrix~ , I don't think we should care about this limitation.

and about weights : as long as it do not affect performances, yes, please raise up everything !

**Comment by theod** [comment]
I have raised the MAX_NUM_SOURCES and MAX_NUM_DESTINATIONS to 1024 but I haven't changed the MAX_NUM_WEIGHTED_SOURCES and MAX_NUM_WEIGHTED_DESTINATIONS because it will change the size of a matrix that is used in many places so I'm not sure this will not affect performance.

**Comment by jln-** [comment]
mm... but that means that j.dbap is kind of half broken, then? That is: one can set some speakers but not their weight. Do I understand correctly ?

Does increasing that matrix max will affect performance no matter how little speakers/sources there are ?

**Comment by theod** [comment]
before the number of elements and the number of weights was already different : 
const long MAX_NUM_SOURCES = 128;
const long MAX_NUM_DESTINATIONS = 128;
const long MAX_NUM_WEIGHTED_SOURCES = 64;
const long MAX_NUM_WEIGHTED_DESTINATIONS = 32;

I guess this was not take to much place in memory (@lossius ?)
now we have raised the maximal number of elements if we set the number of weights to 1024 it means 1024 * 1024 * 4 octets ~= 4,12 Mo !

however, after looking in detail how this matrix is used in the code, this should not affect performance as there is only one double iteration over the whole matrix a initialization (where all 1 048 576 values are set to 1.). else where in the code the weights are only read or write depending the number of elements.

so it means j.dbap will be longer to load (and this is not depending of the number of elements) but the processing itself will take no more time.

**Comment by theod** [comment]
after a try it seems to not be so long at the load. I commit a version where : 
const long MAX_NUM_SOURCES = 1024;
const long MAX_NUM_DESTINATIONS = 1024;
const long MAX_NUM_WEIGHTED_SOURCES = 1024;
const long MAX_NUM_WEIGHTED_DESTINATIONS = 1024;

**Comment by theod** [comment]
this needs to be tested by @matcham and @jln- before to be closed.

**Comment by matcham** [comment]
current j.dbap version (latest Jamoma-nightly-builds ) crashes Max on object creation ::: 


Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000003ff00000

VM Regions Near 0x3ff00000:
    MALLOC_LARGE           0000000010197000-00000000101e8000 [  324K] rw-/rwx SM=PRV  
--> 
    MALLOC_TINY            000000007ae00000-000000007af00000 [ 1024K] rw-/rwx SM=COW  

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libsystem_notify.dylib        	0x99b8325a _nc_table_find_64 + 42
1   libsystem_notify.dylib        	0x99b832a5 _nc_table_find_n + 32
2   libsystem_notify.dylib        	0x99b81809 token_table_find_no_lock + 44
3   libsystem_notify.dylib        	0x99b816a3 notify_check + 82
4   libsystem_c.dylib             	0x926be2bb notify_check_tz + 30
5   libsystem_c.dylib             	0x926bdf01 tzsetwall_basic + 48
6   libsystem_c.dylib             	0x926be1be _st_tzset_basic + 398
7   libsystem_c.dylib             	0x926bf76e localtime_r + 47
8   com.apple.CoreFoundation      	0x9176ab84 __CFLogCString + 180
9   com.apple.CoreFoundation      	0x91819c50 _CFLogvEx2 + 288
10  com.apple.Foundation          	0x91b6f518 NSLogv + 161
11  com.apple.Foundation          	0x91b6f46f NSLog + 27
12  com.cycling74.Max             	0x0036c82e cocoa_utils_outputdebugstring + 108
13  com.cycling74.Max             	0x000b9535 cpost + 114
14  com.cycling74.Max             	0x003138d7 max_malloc_error_break() + 26
15  libsystem_malloc.dylib        	0x989ef76c szone_error + 246
16  libsystem_malloc.dylib        	0x989eff44 free_list_checksum_botch + 50
17  libsystem_malloc.dylib        	0x989e6aa0 small_malloc_from_free_list + 1028
18  libsystem_malloc.dylib        	0x989e38f3 szone_malloc_should_clear + 1292
19  libsystem_malloc.dylib        	0x989e33e1 szone_malloc + 24
20  libsystem_malloc.dylib        	0x989e338c malloc_zone_malloc + 75
21  libsystem_malloc.dylib        	0x989e217e malloc + 52
22  com.cycling74.Max             	0x004f9d6b juce::HeapBlock<juce::PositionedGlyph*>::realloc(unsigned long, unsigned long) + 47
23  com.cycling74.Max             	0x004f7e54 juce::GlyphArrangement::GlyphArrangement() + 54
24  com.cycling74.Max             	0x00238d81 t_jtextlayout::t_jtextlayout(t_jgraphics*, _jrgba*) + 39
25  com.cycling74.Max             	0x00230318 jtextlayout_withbgcolor + 45
26  com.cycling74.Max             	0x0022feff jfont_text_measuretext_wrapped + 42
27  com.cycling74.Max             	0x002f540e textfield_getlayoutinfo + 750
28  com.cycling74.Max             	0x0017fe85 object_method_imp + 326
29  com.cycling74.Max             	0x0017d767 object_method + 149
30  com.cycling74.Max             	0x00209c51 jbox_measuretext + 150
31  com.cycling74.Max             	0x0017fe85 object_method_imp + 326
32  com.cycling74.Max             	0x0017d767 object_method + 149
33  com.cycling74.Max             	0x0020cafa jbox_premeasuretext + 140
34  com.cycling74.Max             	0x0019cba4 object_style_attr_setnamedstyle(object*, void*, long, atom*) + 60
35  com.cycling74.Max             	0x0018124b object_attr_setvalueof + 156
36  com.cycling74.Max             	0x001c6d7b dictionary_getattribute + 208
37  com.cycling74.Max             	0x001a057b object_attr_style_process + 103
38  com.cycling74.Max             	0x001696da attr_dictionary_process + 33
39  com.cycling74.Max             	0x00254e2b jnewobj_new + 3296
40  com.cycling74.Max             	0x000a9f2d typedmess_fun + 393
41  com.cycling74.Max             	0x0017f683 object_new_typed_flags + 285
42  com.cycling74.Max             	0x0017f8df object_new_typed + 47
43  com.cycling74.Max             	0x0026dfe8 jpatcher_newobject + 389
44  com.cycling74.Max             	0x0027af5f jpatcher_pastefromdictionary + 904
45  com.cycling74.Max             	0x0026ed86 jpatcher_replace + 1722
46  com.cycling74.Max             	0x001806d5 object_method_typedfun + 140
47  com.cycling74.Max             	0x0018060e object_method_typed + 129
48  com.cycling74.Max             	0x0020e706 jbox_swapme + 146
49  com.cycling74.Max             	0x00255dd1 jnewobj_enter + 1902
50  com.cycling74.Max             	0x0017fe85 object_method_imp + 326
51  com.cycling74.Max             	0x0017d767 object_method + 149
52  com.cycling74.Max             	0x0028a776 jpatchercontroller_entertext_imp + 299
53  com.cycling74.Max             	0x0028f900 jpatchercontroller_entertext + 214
54  com.cycling74.Max             	0x001e6821 TextfieldComponent::endEdit() + 535
55  com.cycling74.Max             	0x001e4dbd BoxComponent::endEdit() + 157
56  com.cycling74.Max             	0x001e4977 TextfieldTextEditor::keyPressed(juce::KeyPress const&) + 903
57  com.cycling74.Max             	0x004b9e81 juce::ComponentPeer::handleKeyPress(int, wchar_t, bool, int) + 345
58  com.cycling74.Max             	0x00541067 juce::NSViewComponentPeer::handleKeyEvent(NSEvent*, bool) + 471
59  com.cycling74.Max             	0x0054111d juce::NSViewComponentPeer::redirectKeyDown(NSEvent*) + 57
60  com.cycling74.Max             	0x0053db10 -[JuceNSView_1_52_105_3 keyDown:] + 157
61  com.apple.AppKit              	0x9810bf9b -[NSWindow _reallySendEvent:isDelayedEvent:] + 8478
62  com.apple.AppKit              	0x979ef3ca -[NSWindow sendEvent:] + 526
63  com.apple.AppKit              	0x979eb9c4 -[NSApplication sendEvent:] + 4765
64  com.cycling74.Max             	0x003f30a8 -[MaxCefApplication sendEvent:] + 130
65  com.apple.AppKit              	0x9790bbfc -[NSApplication run] + 1003
66  com.cycling74.Max             	0x003f2ff9 -[MaxCefApplication run] + 58
67  com.cycling74.chromium        	0x00e47c6e 0xd1b000 + 1231982
68  com.cycling74.chromium        	0x00e4754c 0xd1b000 + 1230156
69  com.cycling74.chromium        	0x00e8afd2 0xd1b000 + 1507282
70  com.cycling74.chromium        	0x00ea5c7e 0xd1b000 + 1617022
71  com.cycling74.chromium        	0x00e8a9ba 0xd1b000 + 1505722
72  com.cycling74.chromium        	0x00d93ade 0xd1b000 + 494302
73  com.cycling74.Max             	0x003f3007 -[MaxCefApplication run] + 72
74  com.cycling74.Max             	0x00546237 juce::MessageManager::runDispatchLoop() + 589
75  com.cycling74.Max             	0x00408ad4 juce::JUCEApplication::main(juce::StringArray const&) + 62
76  com.cycling74.Max             	0x00408be9 juce::JUCEApplication::main(int, char const**) + 73
77  com.cycling74.Max             	0x0007cd15 start + 53

**Comment by tap** [comment]
I'm not really sure as I didn't investigate closely, but the the code changes here look highly suspicious to me.  The size of a Max object struct cannot be larger than 32K.  The the size of a one array of doubles that is 1024 is 8K all by itself.  So the stack might be getting corrupted as a result of too large a struct.

Large amounts of memory like this need to be alloc'd on the heap and stored in the struct as pointers rather than as values.

**Comment by theod** [comment]
ok. I discussed with Mathieu and he says me it was not necessary to get such high value (he found another solution using a jitter algorithm without weights). so I set each variables to 128

**Comment by theod** [comment]
@matcham could you test it again once you managed to build ?

**Comment by theod** [comment]
I've finally revert all the changes I made as I also experience crash if the weight table is 128 x 128 or more. so we are like before this discussion : 

const long MAX_NUM_SOURCES = 128;
const long MAX_NUM_DESTINATIONS = 128;
const long MAX_NUM_WEIGHTED_SOURCES = 64;
const long MAX_NUM_WEIGHTED_DESTINATIONS = 32;

**Comment by theod** [comment]
I decide to close this  issue as it implies no change finally
