### ISSUE TITLE
j~ is not building/loading properly

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#780]
After recent changes to build solution, the j~ object is not building/loading properly on the dev branch

**Comment by lossius** [comment]
The dsp.externals.loading.maxtest.maxpat integration test can be used to verify this issue.

**Comment by jcelerier** [comment]
This should be fixed as of f62888d096e22609001e5662beed1718819ee0f9 in JamomaCore:dev and 7c9cf0d177bff71484e8f44491e0700dbecf20e3 in JamomaMax:dev

**Comment by theod** [comment]
it is fixed !
