### ISSUE TITLE
CMake may fails on case sensitive OS

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#782]
in https://github.com/jamoma/JamomaMax/blob/dev/source/j.init/CMakeLists.txt#L8, and in most other CMakelists.txt, we use a relative path to CMake modules : 
`../../Shared/Cmake/MaxExternalCommon.cmake`.
While the folder "CMake" have a capital "M", see https://github.com/jamoma/JamomaMax/tree/dev/Shared/CMake.

This is not critical because by default OS X is not case sensitive (I don't know on Windows). But it could be (if someone crazy (like me) reformat his drive in a case sensitive format) but this is easy to fix.

**Comment by jcelerier** [comment]
Fixed by 01e18394d4fb2ed5a7af6a1d4d4ac8e33523c05e
