### ISSUE TITLE
why jamoma_init() and common_symbol_init() are called on each setup ?

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#783]
`j.loader` calls `jamoma_init()` and `common_symbol_init()` on its main function (https://github.com/jamoma/JamomaMax/blob/dev/source/j.loader/j.loader.cpp#L142-L143).

The same functions are also called each time a new class is created, see https://github.com/jamoma/JamomaMax/blob/dev/source/classwrapper/TTModularClassWrapperMax.cpp#L742-L743.

Since `j.loader` is needed to load any other class, I 'm wondering if there is a reason for this ?

**Comment by theod** [comment]
common_symbols_init is part of Max framework so I let @tap explain what it does.
about jamoma_init() there is a static boolean to know if it has been already initialized so it is put everywhere but fully executed one time only : this is to be sure that all jamoma framework initialized what ever the order of the instantiation of the externals.

**Comment by tap** [comment]
common_symbol_init() also is setting up statics so that we can use pre-made symbols like _sym_nothing instead of calling gensym("") all over the place -- thus avoiding hash calls and just comparing pointers for symbol checking.
