### ISSUE TITLE
Use of UI_EXTERNAL

### ISSUE THREAD

**Issue by jcelerier** [jamoma/JamomaMax#785]
While reviewing TTModularClassWrapperMax.cpp I found a lot of `#ifdef UI_EXTERNAL`. 
However a quick grep of the Jamoma tree shows that there is nowhere a relevant `#define`, either in source files or build scripts. Are these parts still necessary ?

**Comment by theod** [comment]
it was relative to former TTGraphic module.
I've removed those lines from the code.
