### ISSUE TITLE
j.cue : can create only one cue !

### ISSUE THREAD

**Issue by matcham** [jamoma/JamomaMax#786]
j.cue can only create one cue, then stops working.

open j.cue.maxhelp
click on 'new init'
then click on 'new anotherCue'
then 'edit' : cue 'init' is ok ; cue 'anotherCue' is empty.

**Comment by jln-** [comment]
confirmed. This most likely was introduced very recently as my build from last week was working fine (afaict).

May I emphasis the high priority label ?...

**Comment by avilleret** [comment]
good to know, I noticed such a strange behavior in Pd too (which code is raw copy and paste from JamomaMax)

**Comment by jln-** [comment]
@theod From what I can tell, it seems the problem appeared after the fix you made for the sub node selection bug we talked about. Checking out commit f5dc9f7bf4a74c94bdd227c1ae52f10f3db96fec [f5dc9f7] from Core repository remove this ticket problem.

Hope this helps...

**Comment by theod** [comment]
sorry for this trouble : what I did was actually unselecting the namespace during the process.
I've fixed it.

**Comment by avilleret** [comment]
where ?

**Comment by theod** [comment]
sorry, Core dev branch
