### ISSUE TITLE
j.cue : interpolation (mix) : do not respect @repetitions/filter 1

### ISSUE THREAD

**Issue by matcham** [jamoma/JamomaMax#787]
when mixing 2 cues, j.parameter @repetitions/filter 1 always output values on each mix message.

example patch : 

<pre><code>
----------begin_max5_patcher----------
1014.3oc4Xs0aihCE94jeEV7bVVaty7zLurRqz7Onppx.totBrQFSmzcz7ee
M1XBoIgPSZixtyKbwXeNemuyEev+b4BmL9FRiC3Kf6.KV7ykKVnGpafE8uuv
oBuIuD2nmlSNuphvjNqLeSR1H0iWvALtDHHM0jbI3qBRMQRkTNq4OejVJIB.
xtnRJijyaY5U50OXMVl+Dks9AgZ8FDg7CbigPHxaE.kl3BU2Bgc278cgf66W
IsPi.d1y+gGzpCVaEkURjZTi5GrQ9ZIQO4QSi2JsyC1M3uVtr6xpYRHUjlF7
ZxdDREcC.CPtfL.z0YBiDEpMrXsggPZyzy6v1Gx2JoG4LICWYrluIn3xwHHm
WxEF4qE61KnQBdGNxalbDZD.Zn+idpHEb6G1LS4q0Di5cbFTWsJ3PE5f6BJF
Q.dowZWZj+XjNrp0BbAkXhUrJIa8NFXDJMBlLrV+HXbRP2SwP0WPChJasJRr
TuzGrHbq7OvjzWQWhZzW8FjPR3p2bar+XuEZWmWZmFzJEll.CLO0oziK.Las
wO5oir1eB0BdMWz4LzTqqe5gjRqjuiGvMN8LRRxZkRkdNdVfuI7uKtWcMvd8
f4.dWTNN5XApYJF6jAqVb9lX0yfRdrjq.1jTRjVUH8sP3j0EPaqKHpvZIDMH
ZgpNgp.7CDFNyvMvKgA8NZp9pAV7SLFIAd5XjzO0Pjyv3TJHiHlv3BfQaS.l
1YG67+NOaP3nP8ocs92Zt1cSjeAKF1V13zuCc+oyxQgyvwiRdeY4nO6XAqnv
uPJd.KkBpxUS19TSOs0yacrSYKg+ncX63iguhMWeTFbmY17jZ6q4MUK78Ov2
nrWnMTKkY9tNDvd68lpS9gxYsW+fO6NnRP0q+024XUWxc3BTPxoU3xo6YdhP
mDjt+IDZxXmKqj3jQCmWdywZbVwefLm48WAgotpdnBCmzxic9H528PM19Aa0
3Ir5XcGG81azj1azsj8t6FeGn5n+8mdWwj4TbLv42gRg9yuTn++MJE92LagP
JSRVqF68VHrOJwrEpWR5jgI2ZkAOJGk2RNY8.OS+h96WPXd+fbj5uI8SODOE
De5SZ3hnvYe9A6wrZ3pODo2bxUZZpa7co6FdqH2JN6on.1RUEjFIkgs+I7ca
IfQS5IZQAgMtC6BZSW0khievQyFOdy.OWQ3jNC3z8GmWK7LC3jd0PS7bHmaK
ek+0CNIygctdNKT7GQldEsnlq1bpubCJHv0ydrzP0yg5NTBsusUceb1QzMVE
q43lCNS3XpuiqqegHZ5koFIpMNe1roV7J8qTl4UsDcDjttWLyW2ciCVn11Tp
1yrUX1RZSho4XmJdAQvZo8M5nz7uV9uvFKkc1
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
good news : it seems that the work @lossius have merged yesterday fixed this bug.
could you pull on Core and Implementation/Max on dev branch and rebuild everything to see if it the same on your side ?

**Comment by matcham** [comment]
yes, it seems to be ok now, thanks !
