### ISSUE TITLE
j.cue : mix : adds 'jittering' to parameter @type integer

### ISSUE THREAD

**Issue by matcham** [jamoma/JamomaMax#788]
open j.cue.maxhelp
tab "interpolations"
click & drag anywhere in nodes "1" (without interpolating with another cue) and observe /degrade~/bitdepth : value "oscillate" between 22 and 24.
(it should stay on 24, as there is no interpolation with other cues)

**Comment by theod** [comment]
a patch to reproduce and debug the issue : 

<pre><code>
----------begin_max5_patcher----------
865.3ocyWt0aZCCEG+Y3SgUTejlEmDxk81dXeJpllLIlfoN1HaGJcUae1msy
EBPHTQA0JghHmXGe9ct72NuMchyB9NrzA7cvSfISda5jIVSFCSZtehSIZWFE
IsCyIiWVhYJmY0OSg2or18gslXUk7JEEqrSvqw5FjJaEgU7aANSUufvfD24y
.Idtdy.9ysW0+G7qloPxsuY9h0Ol19xkpWoXq4dKGg0tZPis+Ncp4xrOJQgW
KQv4Wln3OChBtVhBiuLQQ2QhJwRIp.eBQdt9QIQdA.OW8ugoC1Xs1j50M3Zz
bb5nXHviluG7zHK39CCd36Db+aJ3y8B7ihtafWWCON3AeJfCCShChuafWKGM
N392QvWXcMrn8EhXLtBoHbl8wLNqKnrkfeYKQRVPnD0qGP9xkRbCWVd52yR4
YOiyyEnBYlfSo8k.xnjrmUqD7phU8siYnET7pSmP8C1d5CVTTxywGXgKx0b0
WvQfkZgJKc8yD1Zu1qV+OtO.2xx7zzysJ8ct9qSu5fjtrNprtLHGWHP43+4Z
xMt5DqdoGVErM8JJZ1+04asSV63WQgCC+h1mNSYyOKqnHEFnVgAURLfuDP4u
fE.IpbCE+nP+PI.wxAKHpG0jyoUlI6dRCXGglzKc3FvfykRjjBFROo9+azzj
OL1jl7S7sckIi0UB6ziVxYptTxODDD87MrlwtDkcPk5gMw8Fnj7G6.gZW3FJ
pIvnbvZ2rJrKdmMg3p1otoha13GDVe9D+wiivqINduhYGVV2ExrQqgiPsKdF
mxEsZfoIo9yiLBggv3vHeqjX.LIzDO5EGNMrN68EZqERBF+jBwe3HK79WMVR
1AffGf.evC9f.vCA2iyWzTJ5kN5FsImFVxwKQUT0E2v099bnD1wefi0oL1OL
1H4UhrVDZ1kGr2qxwREg0on9zdGr2fVQxywr9RI4DoYCRKRCmjdutSvWK2I7
qk6bzRMr+X5+F0eJI4a3DlpohAFWeFjXnquYWHnsj0d29U5lgfQ28liPiOGk
1m.6cWjf5FHzlMawBYiWXcdsLx5Zk03Y1aIL99y0o2Mybnz5wO2ZAIzp.JsD
PkntGdWR8WK5XNDgfUQZ9vPcXaZSu9QMschkqaNermWy1T53qPeNsi0Mczm3
QQZYxPyz+N8+ru33vA
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
ok it fixed now !
