### ISSUE TITLE
j.parameter type array: j.remote returns ramp function with unit appended

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#827]
When setting the ramp/function of a parameter of type array, j.remote returns the unit used as well.

See the below patch:

<pre><code>
----------begin_max5_patcher----------
2769.3oc6b00aaiiE84zeEB94TO5KKYOOM6NXwt8gE6rXdrXP.sLiMajHEDo
RS5f4+9xODknDojkShcbWTfVqvKont7PxCO7RY+me3lEaIOAoK79YuO6cyM+
4Gt4FoIggaZReyhBvSY4.prXKJfTJXObwsp7XvmXR6THyCBnvOg+6frG7d54
uoKBolkCYrmKgpmyhEd+QSV35BDlmorpCaLVBXYGP382UAyXpaYyp0K8u0KI
JTbIHHVbIjmnslP6jdAY6W9Xfu9IWVAoPLCvPDrYskrRb+oQAhK9MeX5TJWV
5UAMVormykMfEKDF9qO7AwG2dMiZqCOATayhyXyGC+J+YX05+V9RZNJC5ENd
q91Wz3kjMh15pXYm6pzoZ3Ita3gmyFNsdKkgX0LnmXD.++zmK1RxOSv.+xJ9
.fnMSNsI3c.H9xxJXAgCCEOeWIghDyT+4JPQ4OceMNSjZZH41IglfiCMARNf
fMSNDI0MxDagL6f2CpyYuD.pt.hqGswhvrWcaMNQRG3ZXPIfi4PFr5NHFrU0
X7swgnH2.QjtnLXQyhIKxQXHnR3v2J93is+UGc2.S+mZlkUW132LgO3.531s
s615mv+JpJqN2vAaqDm4LlcdEUuEk4nVrL6z3mv+C9H.lqZvUFiXlWKOURv7
k5PfbG0zHYNQVeB+eqA6p.N8L2YMZFx5pZrZpxc8T4pV3yBbWK1YLh4Og+c9
3R6pvx5PaFiec.Y2WAgG.3csFxI6AUH1gBCKesTLWWmtj7UX2XIZAgvN7aj7
mwjByZlAvGb3Da4.jfgnyPNeZRA.aY3eAppPzdd+NXGnrGTa3TG.EbJk8Fow
XyzO.PTCuFWyXf7NmUP4.v66MKohvkfsEVs+elSDk92pyocvJqBTB+FA0gbr
5GfO2l5qv7rCcLdeOuXb5pv4uXbT34bw3bzivklq27HnByW.neleN3OZERix
X0Uv9b6KoOtuOgdeKMb2lFcXRylaeuVlcZriJ2pFbkwHla3wsqhgVcYqkD25
1cX2s0dL31Ui67FOGC5aqJyYNiYuk61U0T4rRpbTERhXGUgkc2VUr1V2+PiC
MYiMZdZc5VZ5NCRVZcRIIsNwPNZscAEs9u07xsoaXgGlVwJa5obRYcRImrNQ
CkbWRIirNohPVmpgOVmzfNt0jK131FhlLt0ffKVmPREKSzRXMpl76yI.VW4t
mfYTz2jkJRrkrSS+ZCyYbhuf4LUtmtnTChyZJrggpeMYKpMvw9dBmVTKE7Hb
2c.FqBskuFQ2eQaXXanXErn40Px8ZyZ6ldRNAu2ASanlosWgoGHUL6R6pn59
fPG4wukBKQ48UgaI.ef16gxtcn31RrssNamRrcntdfvZaM0CkSaoj1kHZa8y
NkNOlpY2BlcnU1sLYWJjsDG6RWrsjXK0vtDBaqAtu7WKkuCD8NPkqo.2dZaM
j01pn0kXVsNVSgqlZVskqZnTsUjpg9TCoocpRMDjNPK5nxP6o.sU7oV2oZ1j
Tdk9x24A9PKCcVA9X8EHvGYjBNqFyBg92fGfTO1AD0iqPW1R7.dE7wD425QI
7b.LuVXj6s7lH0KCfEEmlw4ngdLBuDsLg5BsT+rDzgYbBKlIe+15sCVrXtP6
ZEll1DuwlfOFLR31bCs9m2nsIguWxFaN9Hpzz.wxywStulP+2gfLV5sCQKyA
OeGBeGli.zSMH6Sz5CCkgUONHQEj8noZ9qhlcT1MehbxsARMtGkCeDVQE7Dc
2+MK.kkFl6qBo.7EhrhRaEIvahJS9slpfOhz2eTqUPEucyfsZrV7TRbmNDwn
pJbMR5JZJSsK0AU9sG2RhZtQ7Ziycg24tOmj8.bmoCsfTB477lmjSuraHdty
ThYP3Rm4eOHCN5M2py5uUIWxpoH6qP6HXgSzCmEl0OtO6EHOOIwmcMFYIvfR
G2bCMj6Lo7FYMkuLonangHRqpaAiPx6mU68kCum0jcIBiGfhLR43YVg1eXh6
cKeASRwT0sLG5c0XUt2IjXcmP2b+xwWYtYFZ+p+I.FU.XPFR0ED52loR49AN
cNgurtY6UkyiNxYGeDbF7qncrCxGj4fAw5Bk5AQKZ6k2g1Cor91Xf8z9Vrlc
dyB8JSBI3vBNGCaPA5c9plSGM4x5YeJNsAAtJCjC8BV58Q9+8Wx+KyhMN2lM
+VhQFN33BTG+ZPnjaeSxPJNKZN+E8eR1TctX6MjZoY8eiQrRwgr5K.qWJREN
MRsRxqErNUcvqGCnh2bkBT7oxyCpT6z2ZK+itD5Q.Ne4kziNBKd83.W36Ivo
lSJlPdlmS1.XycJYb564HMYq5kBD9yAHTBJhZ+bTpofSFGLrp2qxaM9nbhEu
p4NgpS4cFPP33Pf+qFB5T.I1c0HK8IaDh7ciMTRcUldjgtWyqeChuVNCgaED
94NdgAE7.Z2NHdXiiui.g9AkRlY0Sdx9r+b8Y9h.dAWE9rzUliOKFCckfyxt
7f43y9WW97rFajd83yomx342BetI7a5sR1DId0tmlHL7mjJe9VN2Bxazv2tG
voj72sufWQPAmNHD1A2qaul9KW8hiQwJY7ohTp4kWZqpm46cIywifu3.EJ1e
e+S2dVutPw9lghIijqh0fYf.NxKeoNlbOMh20DWmGvjsucurhiEPxe8..uG5
wN.8DAp0SGnVu6IUdfc6jwvEj6AeRDsBJ5QnWIgecKJmmErKriyNvZAqWFJB
oVPppCKZYJOYn+Huy.qmNjhp.aRQ86KOSXEnhOyDAvdYDR0NAIAj5wgk5blG
B6UPdDJtQOf3Dw7.dTVEPDFBOAiz4J.sq7WoTJEJeELRRlJ.sQomyHzNFv86
kbdHDeSDi.bbjpDUA3.y9VP7bAWwom.ZkbJC9hNug6ETyHE.FmtYLJ1s.by4
0i2ORLe8OJeZPp5LTVGN4qxS7rC48+GFy2UaT6qO9Gg88Gg88Gg8c1QDfQ1u
OGNYHSDuS3u13sEoBQYr9yd02Dx7rH4BtRCjYNArS7kuwK3kF9oSJvkgGKNb
gWqQ7k2QWQ3sFe+IApdKX9RCOtRJgZ0yIAq0umf0EZJXyafwqdJ35qzAVTXt
m+Ql90SN1sSNcLZVwBMp4MF7XivRFGzhN6f1aQTeiTeq9NdTeiNqQ888ABVu
5zffnu6B78biSXxUSXBSlYzXEcFWQt7b.4nqmfdGM2CDI754.QBm6gK3nw8t
4yycB35eDy6iDsFteyl3sZchHwLQHphTuoEg9gtEQ0SMY547q39Yo40Dno40
7hV7N7CXf7MDQ7OYHwi619vawOfA5d2zT0drVO4qVZ36Q6OMTi.od.3tyBLn
GEz.CqBl7qw+6wOjCluj0FuP6d+hnc6App.O68K6.L.sDjIOVjl7qwHl4u5E
8hfc7a66obCLFEqBdqJVjIiMZ5k7dJKqn9x+Tf5vkcZfVqka5cDqirRi3m2j
NEV1KyXuDiUe7bcm0yvc1bU4M8kncVcm4zWkbw7lj4LxI3h4Nqhlg+D6ew7G
wgvXLLcDsxoWV+4X3SXzkyehlA9bAgmv4Lb9Xy0KP6JIHLqgLNMQ9ETY0F4W
.+z3H6TwwpTpRJSY9tF7F05BmC0Q3kiIKbNSVC1b47m4z6eAgmY3MqtbSUGz
Q7diNxYgGi4X8kycBliJgnSi4XS5ZAePh5Pd1rJ0NUr5K8WSIkoNJygRt3fi
uWzvFbr8CNxd6iqe7ipe3wzyex+0G9e.GOW66
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
this should fixed now (on Core/Modular). could you test it @lossius ?

**Comment by jln-** [comment]
It is fixed. Closing this issue.
