### ISSUE TITLE
How to properly build JamomaMax with CMake

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#835]
as @jcelerier told me it should be possible to buid JamomaMax with CMake, but actually if I can configure and build with CMake and even make a package, this package contains no working binary.

Each .mxo externals is a folder rather than Mach-O bundle.
For example : 

~~~~
$ tree j.loader.mxo
j.loader.mxo
└── Contents
    ├── Info.plist
    └── MacOS
        └── j.loader
~~~~ 

While when building with ruby script I have : 

~~~~~
$ tree j.loader.mxo/
j.loader.mxo/
└── Contents
    ├── MacOS
    │   └── j.loader
    └── PkgInfo
~~~~

Thus the package is not loaded in Max6.
I've put the bundle here : http://dl.free.fr/fsPxsSk8x (available during 30 days)

**Comment by avilleret** [comment]
Note that I can make a Mach-O by copying the `PkgInfo` file in `j.loader.mxo/Contents`.
But it still doesn't load in Max with this error : 

~~~~
j.loader: unable to load object bundle executable
 2015-04-12 12:07:16.675 Max[27420:707] Error loading /Users/LaFabrika/lib-src/Jamoma-CMake-build/Implementations/Max/source/j.loader/j.loader.mxo/Contents/MacOS/j.loader:  dlopen(/Users/LaFabrika/lib-src/Jamoma-CMake-build/Implementations/Max/source/j.loa
 der/j.loader.mxo/Contents/MacOS/j.loader, 262): no suitable image found.  Did find:
 	/Users/LaFabrika/lib-src/Jamoma-CMake-build/Implementations/Max/source/j.loader/j.loader.mxo/Contents/MacOS/j.loader: mach-o, but wrong architecture
~~~~

but this could be another issue

**Comment by avilleret** [comment]
According to [Apple Developer Documentation](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPRuntimeConfig/Articles/ConfigApplications.html), PkgConfig file is not needed theorically.
But in the real world of head aches, it seems that without this file, the bundle is recognized just as a regular folder (I tried to take a Max external [acos] and remove the PkgInfo) even if all informations it contains are already present in Info.plist.

So I guess we need to manually copy a PkgInfo file into the bundle.
Just like what ruby script does :-)

**Comment by jcelerier** [comment]
Well weird, it worked fine on my mac! Maybe it's only not needed since Yosemite...
Anyway, to do it it would be a matter of adding 

    install(FILES ..path to PkgConfig file.. 
              DESTINATION "${JAMOMAMAX_INSTALL_FOLDER}/Jamoma/extensions/${PROJECT_NAME}.mxo/somewhere"
	      COMPONENT JamomaMax)

in https://github.com/jamoma/JamomaMax/blob/dev/Shared/CMake/MaxExternalCommon.cmake at the end near the other `install` commands (it needs to be here for j.loader too...). (Can't test right now, sorry!)

**Comment by avilleret** [comment]
Yes you're right it's working on Mac OS 10.10.
By "working" I mean, Finder displays externals as bundle not as regular folder.
But the Info.plist file is corrupted and I can't load them in Max, but those are other issues :-)
