### ISSUE TITLE
model loaded inside poly~ : avoid lots of warning

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#839]
When loading a model inside `poly~` I got this warning for each instance :
`patcher: No name provided to grain~ model. Using grain.11.`
Unless I provide a name with poly~'s `args` argument.

It may be less verbose, one warning should be enough.

**Comment by lossius** [comment]
I don't think it is possible (or worth the effort) to make this less verbose. After all, each poly~ instance is a separate patch, so when you make a poly~ with 12 instances, you are in practise making 12 copies of the same patch. Each of the patches will contain a model instance, and each of those models will then produce error messages.

**Comment by bltzr** [comment]
is it useful toi have these warnings at all ?

**Comment by lossius** [comment]
Thjese are just the same warnings as you get outside of poly~ whenever you do not provide a mode with a name. I'd say that yes, these warnings are useful.

**Comment by avilleret** [comment]
I see at least 2 solutions, but I might be wrong.

- display warning for only the first duplicata (instance.2)
- do not display any warning if j.model is inside a poly~

**Comment by lossius** [comment]
The code for this would be complicated and IMHO not worth the effort, at least not for the time being.

**Comment by bltzr** [comment]
The funny thing is that warnings are not generated when a model is only made of sub-models (ie without any parameter at the root level…)

Apart from that, I don’t see why we should have a specific behavior for poly~s… For me it’s just the same thing than duplicating patchers manually - just that it’s done automatically

My solution: not looking at the Max window ;-)

BTW, did you try adding @args modelName.1 to your poly~ ?

**Comment by avilleret** [comment]
> BTW, did you try adding @args modelName.1 to your poly~ ?
yes and it didn't help

> My solution: not looking at the Max window ;-)
maybe I should try that...

**Comment by avilleret** [comment]
I reopen the issue because it's not fixed, and saying that it's too difficult or not the time to do so is not a good reason for me to close an issue

so please leave it open or fix it

**Comment by avilleret** [comment]
this issue could now be closed since I removed the warning when j.model is inside a poly (without adding any line of code, just adding one more condition) :-)
