### ISSUE TITLE
component jcom.class.gl_group.inspect bugs

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#84]
on max 5.1.8, blend modes are not displayed correctly
scale number boxes have a min value of 0 (negative scale values are usefull do make mirror transformations)
ramp on scale does not work (putting @type before @ramp/mode in the jcom.parameter make it work)

I've attached a new file with corrections. (I don't think I can commit myself).

Jean-Michel

 see more on the original redmine issue http://redmine.jamoma.org/issues/1494

**Comment by reno-** [comment]
j.com.class.gl_group.inspect has been ported to 0.6
The new one is j.gl_group.panel.maxpat, and the scale hasn't clip anymore
