### ISSUE TITLE
j.multi.in~ ≈ : bad arguments for message "funnel"

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#843]
loading `[j.multi.in~ ≈ ]` component leads to that error :

~~~~~
#N: bad arguments for message "funnel"
~~~~~

Please also note that there is a space at the end of the filename before ".maxpat".

**Comment by bltzr** [comment]
sorry, I committed these by mistake... I have removed them from the repo
anyway, j.multi.in~ is not used anymore, j.pack= has to be used instead
