### ISSUE TITLE
feature request : would it be possible for j.pack= to accept packed signal ?

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#844]
Take, for example, one stereo and one quadriphonic sound players.
Both output packed signals, I would like to make a 6 in 1 signal from the both without the need to unpack them.

Does it make sense to your eyes ?

**Comment by bltzr** [comment]
did you check j.join= ?

**Comment by lossius** [comment]
j.join= does exactly this:

<pre><code>
----------begin_max5_patcher----------
896.3oc4Ys0jZBCE9Y8WACOacxM.oyrOzeGc5zIBYciECNbYq6tyt+1Kj.V0
UfnEhzwWXWiwS9tbH4bf2lNwdY7NVps0Ws9t0jIuMcxD4PkCLo5ySr2P2EDQ
SkSyVv9c7x01yTeUFaWlb3nXZ3RpXU8WrklE7DWr5mIrfLU7g.3bvLK2Exqf
xqHzbf0Op9Ih7Mw4YQrL4BAqFMM6kHlbIpCsZRYurkohqsbcOLLbwoQgGJCQ
Ax+Bx2tbr2mNs7xLMoM60PZvGsvNBwqjQPhjjDm5qMPOPiz6H7iNC9WbM3uH
pKYIsS.ExUtjiaG9SMxR4qj7YdyL5wXQ1iz.1g79SlXQbDzH6YV1OVjKk8W+
r7WmxeUNOHZ+xrINjcHNJmlftQsxeKgWFKMETugQPwd36TA0cfDTfycpf5LL
BJB6cmJnjgQPgt98hftMgkxDYzLdr3nv6pBeolHmd4k8A++Oa.OP1.3d8nLz
UInmujt0yyEaoA+5AK2V0ZYdHFqjbLtCw1S+559qNd4+2ETOHrW0r0wbwCVn
tULju5O.rtomcqXz7Pd77fXgnb0ZVFNWpC3ZjgMrzT5J1mzg1xXvXfpRYEw8
m6zWMBnOagK5QSuHq6CM3qORciR+03SU5t1o5P+9zicZqxhEjauG6ZNOtlui
.O1qO8XRqUOt316wDC5wU7cD3wN8oGia6rJEYusdLxbdbMeGAdLtO83VqGg3
dMdbS8nTGMhl8n7ujY.LXlQEutvLiNTIe70pRWb9DrOymfcWe6McOCeClX.F
Kk2g60FYTs9g5tnGj5AG65LN5iY.DAhFcyoDAnim4UAxYta+PUP9qri3hSeS
OR5TN9wRSZbdRPMHpdkIE6OsewCYoYbgbKsClTQKUGNom3ggLwgOmjPdJcYD
SBRvYMo9EOtiL7PFY3AMxvCXbgGeyAmhSSsb5.NHOyhGRW3w0r3A2EdbLKdP
cgGhYwCrK7fMKd551KjA29AnCdflCO5.GvQd5PBGntvwLpCTmMmQlSc7zDNF
Rcbz4nzi1ubPgCVS3fLCbfZBGyj6nq3XnTmE5.GyU1yIEn2.dLWYOmTfdC3w
bkY.04bBn4NVGpywnPykOqy4DWq5nZYltc6yrjzpPJAh8F553j8uHa6h1vUe
TFQ6D1y754ikiPSBdhmUz.edhpc+ctpGmf709mHx4xmlyzxU98o+A3G7f8H
-----------end_max5_patcher-----------
</code></pre>
