### ISSUE TITLE
input=.model : newobj: jalg.sur.input~: No such object

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#847]
when loading `[input=.model]`I got this error : 

~~~~
newobj: jalg.sur.input~: No such object
~~~~

**Comment by bltzr** [comment]
AFAIK, surround models haven’t been porte yet to 0.6

**Comment by lossius** [comment]
That's correct. These issues are still useful, so please keep them coming. I'm adding them to the appropriate milestone.

**Comment by lossius** [comment]
The name of the model is input=.model, not j.input=

**Comment by lossius** [comment]
Algorithm is substituted for model, so closing this issue.
