### ISSUE TITLE
input=.model : j.return: "enable" is not a valid attribute argument

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#848]
when loading `[j.input=]`I got this error : 

~~~~
j.return: "enable" is not a valid attribute argument
~~~~

**Comment by bltzr** [comment]
this should be replaced by @active

**Comment by lossius** [comment]
This issue has wrong name for model, it should be input=.model, not j.input=.

**Comment by lossius** [comment]
This has since been fixed
