### ISSUE TITLE
j.remote output value in wrong unit

### ISSUE THREAD

**Issue by matcham** [jamoma/JamomaMax#849]
when value is set via j.remote's inlet : output is in j.parameter native unit (instead of j.remote @unit) 

<pre><code>
----------begin_max5_patcher----------
1463.3oc4Zs0aiZDE9YmeESQUpsRtVLWXfYeZUecqZdYeKZUzXy3DhfAKXrS
RWs+26bAvDGhM3BY81tRYMyEXNmuy4aNm4.e8pYdKyeRT5A9.3FvrYe8pYyr
cY5XVU6YdY7mVkxKsSyaUdVlPp7l6FSIdRY6+w6ERvNd5VAHoDTJTfcIbf5d
ciGVTHxxUheoDjHS0i7AP9V0lsJyLSj5w2vK3YBkn.H4pjcBvVYhB7qIxRkf
GCxW27L.ezLzuApW+zDoXU9VoUHHUcJ2loW.8JYEY+pdWmKUkI+svzGBu.Ff
Qnvpw1vUqtOQd2sEhUJGbD5GtveN.xvlev9A1VP+E9fuTcWkpmSsONuZwII1
1Le4C+ND4sWbr5sUZfl991UWY9u4+Kw7+55OCt9Sfex6n58xsKW5DSXKjXMe
ksObMBTHJ0qgF9yksPgf.hU8CfKBlC7MW2FALhxp7z7B2r8WDFQvPhYRPRfO
KxNcDN.wzfWqarC.uYo7MKUDxz.Q5Mb62MbWCB28BwDwXQT1b6UTFxcEEyfv
Jw7GLqD0BcPGBNsVIB1sTzywJwtTMRW+oIz7DhrakDvdGrN1UBaMKC03D881
3jIJK42Idkwg.WvvQHeTm65i5zvUK1ttTOuQ3jbOuihe9VFDBGYMX9tMj5K.
FzI.hFQj.EhVPBYzv.uQTqIQ3ET8+BnyADLyRrc3.pupNdzT82hglkDmbGOQ
NTdZG5K0GZMrQVBY3.oIgQSdf8XwpjkhzwSUgLaP0AqprIWUMTYdwnnoTixQ
CNGaZj+nono57WWneJlYU8L4RYtKnfcFxbYCydGuPpS88v67lfuzMjfdSB9b
f25zbt5DLcpaKMKImvbgxagRsM9Mb5lzyuUH4GXI5LVQIemH9VtRUjrbqRr+
pxJfqB4L5u9DC4qq6tt+1qYZt7tNwHXTMH8h4Wdedgp6afz4MTih9cLl4zFM
dN9twsND0+LPuCo3QM19JVPywaxd9Vylbti4.NbOudD2ibLGjl+5iOhNnf1G
A5N3S+CBFhtvnRjIkJQr6udBlD7RmIENTlTvfYRYZSqMW4EPp9f2QmhrAe2H
adSKQhtuxACIipvKsPR3IkGAo8fHQYW5DI5PIR3yfHkXMZZOjEGinA6d3WPx
Hu2Qzh+iuGwxfQNN3PikQilRN3aQzPSCQyUbndQyBuzoYA+mLd0.7QfSiOhl
mny4C46e5iGPoW5NIje7NdP+8.lPyODE1Cy+EeNs3+2EJ9spwxmEYaxK3EIo
OC1VJ.iXozfD2adf4hyFDMr5tPBl7BLcnxOd0VqV2Q3yS2IStt+m1hqAr4es
7YspuluMUMdptq.4CWywStlecyKXlm9H+4RP5dnX7zehusNZvvvAB.vQC.dq
2TvOCOAM+7dUAUIHfPspxZ2Go8.msVZOBO4umDs1u+jFimdCcwDImmdCYild
qCkqeFmQN.K4x65woDHP2KgGddJZvwxMv+X4FrNuHiaEE5XdVz8efIMGG0.L
1fAY7TvGi4Jd4F9JAn0gUe46lnGepIGE56AriXtZthr3Ncv39I2Uw93rZxAe
zOVQxz+KQ2x7sEqpUh5SDCfMRUrnTkHapizMMuGzVy49j3XgrskONoz3LD2j
z7qLy8UbLEa9jhC9cSbzF.f+IjFC4n0jlTwg0G44DhiNJxl7Dopxgg4pjRnc
+Apyc0zX+pLZhuINwzH9HM0pQ7sMl.wm1KuA16l2f4.6mTdN.ymT4IbDLuin
3D0CwgxFl6FgUkuj0siD1QKnKI5pYZaMENi8YqfCffIcia+dHOgvyBsYgN3M
7UMvsgZ7zfzg8g1ef5O4gHOo7fOKjlnOxi4mP5qagIQtpHEzzZJP69Di3.Hn
+nsKcI9lM6DEkUOSqnnS67A22Bm8KHVCORWS6SzqPrKod91uMPOdgNiOkNcu
sEtr3dJxU+Tur7XQgbaRUpZ5U9aW8OLW1+ND
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
I've just added a test patcher. In future a very sustainable way to work would be to make a test patcher like this for each bug we found. I add @lossius to know if the test patcher is correctly written and well placed inside the repository (as you'll notice I did'nt create a type_ repository like in parameter case).

I try to fix this one now.

**Comment by theod** [comment]
@matcham I let you test this (you'll need to pull Core and rebuild Modular only)

**Comment by matcham** [comment]
seems to be fixed. Thanks TO !
