### ISSUE TITLE
sample rate of the j.in/out embedded amplitude follower

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#85]
there currently is an embedded amplitude follower (or maybe measurement) in jcom.in and jcom.out. Very good !

Though, there is no way to turn it off, or to change its samplerate.

Théo proposes that setting its samplerate to 0 stops the measurement. That sounds like a good idea.

The remaining question is : how do we address it ? 
I propose that we add a parameter :
/in/amplitude/active @type boolean

 see more on the original redmine issue http://redmine.jamoma.org/issues/1492

**Comment by theod** [comment]
this is no the case anymore as the amplitude follower is inside the clients
