### ISSUE TITLE
j.cue: optimize message crashes Max unless editor was opened

### ISSUE THREAD

**Issue by jln-** [jamoma/JamomaMax#850]
- open j.cue maxhelp, then tab « optimize cues »
- click « new initialState »
- in degrade model, change sample rate value to anything
- click « new anotherState »
- click « optimize initialState anotherState »

=> crash

Note that if you open j.cue editor by double-clicking on the object before sending optimize message, no crash happens.

PS: setting all red labels, as it is kind of urgent to me... :-)

**Comment by theod** [comment]
fixed !
