### ISSUE TITLE
how to build standalone with Jamoma?

### ISSUE THREAD

**Issue by reno-** [jamoma/JamomaMax#851]
I tried to build a standalone from a patch that used Jamoma 0.6
https://github.com/PixelStereo/dbap4totalmix

I tried to add the package in the build script of Max, but j.externals doesn't load.
I tried to build the patch and adding the package in the support but it doesn't work, even if I put externals in a folder called [Packages]

Here is the kind of error I have with all j.externals
>j.parameter: unable to load object bundle executable
 2015-04-19 16:40:58.893 dbap-totalmix[15435:652436] Error loading /Users/reno/Library/Application Support/Cycling '74/temp-MaxRuntime/mxt/j.parameter.mxo/Contents/MacOS/j.parameter:  dlopen(/Users/reno/Library/Application Support/Cycling '74/temp-MaxRunti
 me/mxt/j.parameter.mxo/Contents/MacOS/j.parameter, 265): Library not loaded: @loader_path/../../../../support/JamomaFoundation.dylib
   Referenced from: /Users/reno/Library/Application Support/Cycling '74/temp-MaxRuntime/mxt/j.parameter.mxo/Contents/MacOS/j.parameter
   Reason: image not found

**Comment by theod** [comment]
@tap I guess we already discussed this orally but could you remind the conclusion here ?

**Comment by theod** [comment]
@jln this would be nice to document once we know how to do it

**Comment by tap** [comment]
I have fix for this.  To build a standalone, you just build it.  Everything should be automatic.  Commits forthcoming.

**Comment by tap** [comment]
I can build a standalone successfully using the echo~.model help patcher.  Assigning to @reno- to test and confirm.

**Comment by reno-** [comment]
Hi Tim,
Tx to work on this. 
I just tried to build a standalone and it creates an app after 3 minutes… but the app doesn't work.
Here is the report from Max Console
https://gist.github.com/reno-/83da3bef6bfd57aecabc
and a quick look : 
![capture d ecran 2015-10-16 a 15 41 36](https://cloud.githubusercontent.com/assets/127730/10543069/9d2b351c-741c-11e5-87dc-e03f4144e77d.png)

{
	"version" : "Beta Version 7.1.0 (c0d54d2) (64-bit mac)",
	"platform" : "mac",
	"arch" : "x64",
	"osversion" : "Mac OS X Version 10.10.5 x86_64",
	"samplerate" : 44100,
	"iovs" : 512,
	"sigvs" : 64,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "cee024a8f01651d64d65b1a916287ab0",
	"eventinterval" : 2,
	"overdrive" : "off",
	"mixerparallel" : "off",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf",
	"packages" : 	{
		"BEAP" : 		{
			"name" : "BEAP",
			"author" : "Matthew Davidson, Peter McCulloch",
			"description" : "BEAP (Berklee Electro Acoustic Pedagogy) Modular is a synthesis pedagogical tool.",
			"version" : "Master from GitHub",
			"website" : "https://github.com/stretta/BEAP/wiki",
			"domain" : 1,
			"domains" : 1
		}
,
		"Gen" : 		{
			"name" : "Gen",
			"domain" : 1,
			"domains" : 1
		}
,
		"Jitter" : 		{
			"name" : "Jitter",
			"domain" : 1,
			"domains" : 1
		}
,
		"Max for Live" : 		{
			"name" : "Max for Live",
			"domain" : 1,
			"domains" : 1
		}
,
		"max-mxj" : 		{
			"name" : "mxj",
			"author" : "Cycling '74",
			"description" : "Max Java Support",
			"version" : "7.0.4",
			"domain" : 1,
			"domains" : 1
		}
,
		"MaxDefaultContent" : 		{
			"name" : "MaxDefaultContent",
			"domain" : 1,
			"domains" : 1
		}
,
		"MaxIntroLessons" : 		{
			"name" : "MaxIntroLessons",
			"domain" : 1,
			"domains" : 1
		}
,
		"Mira" : 		{
			"name" : "Mira",
			"author" : "Cycling '74",
			"description" : "Mira automatically connects to Max and mirrors your interface.",
			"version" : "1.1.8",
			"domain" : 1,
			"domains" : 1
		}
,
		"vizzie" : 		{
			"name" : "vizzie",
			"domain" : 1,
			"domains" : 1
		}
,
		"Jamoma" : 		{
			"name" : "Jamoma",
			"domain" : 4,
			"domains" : 4
		}
,
		"Max" : 		{
			"name" : "Max",
			"domain" : 1,
			"domains" : 1
		}
,
		"MSP" : 		{
			"name" : "MSP",
			"domain" : 1,
			"domains" : 1
		}

	}

}

**Comment by reno-** [comment]
Hi @tap 
It seems that your commit relative to standalone breaks Max 6 compatiblity.
I have this error when I create a j.model  : 

    Jamoma  v1.0-beta.1  |  build dd3782a
    j.model: unable to load object bundle executable
     2015-10-19 16:57:55.476 Max[7686:111585] Error loading     /Users/reno/Documents/GITs/JamomaMax/Jamoma/externals/j.model.mxo/Contents/MacOS/j.model:  dlopen(/Users/reno/Documents/GITs/JamomaMax/Jamoma/externals/j.model.mxo/Contents/MacOS/j.model, 262): Symbol
      not found: _fileusage_addpackage
       Referenced from: /Users/reno/Documents/GITs/JamomaMax/Jamoma/externals/j.model.mxo/Contents/MacOS/j.model
       Expected in: flat namespace
  in /Users/reno/Documents/GITs/JamomaMax/Jamoma/externals/j.model.mxo/Contents/MacOS/j.model

**Comment by tap** [comment]
This is true.  If we are to support standalones then we cannot support Max 6.

**Comment by reno-** [comment]
Ok, I just wanted to be sure. I think that building standalone is a big step forward, and I would definitely accepts to jump now to Max 7 . I will send a mail to the Dev list, because we need to update website and documentation mentioning Max 7 as a requirement.

**Comment by tap** [comment]
Hmmm...  Looks like a comment I was leaving never actually got sent...

Here is the process I use for successfully building a standalone:

1. Open that help patcher
2. Save it as a project
3. Add an instance of the `standalone` object to the patcher
4. Save it all
5. From the project window, choose the thing to build a standalone at the bottom.
6. Switch from collective to app, but leave other stuff at the defaults.
7. Test the standalone.

**Comment by reno-** [comment]
It works, thanks a lot @tap !!!
