### ISSUE TITLE
Jamoma/Modular/j.parameter/type_string/default_attr_value/value test fails

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaMax#852]
Even after updating the test patcher the recent change about outputing "none" for string can't pass the first test. I added @lossius to this issue to warn him about the known trouble.

**Comment by lossius** [comment]
This is an initialisation issue. My guess is that the default attribute is set when the object is first created, but the value attribute is set after a defer of some kind. As this help patch fires from loadbang, j.parameter has not been properly set up yet.

I have a fix for it, and hence assign this issue to myself.

**Comment by lossius** [comment]
Fixed.
