### ISSUE TITLE
What's the aim of feature/split-modular branch ?

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#853]
I saw the feature/split-modular branch and I'm wondering what is its aim ?
The name makes me think it's for making a Modular only package but this is already possible with CMake.

**Comment by jln-** [comment]
Isn't it related to the split of j.modular into various protocol-specific externals (j.osc, j.minuit, etc.) ? @theod ?

**Comment by theod** [comment]
yes it is. 
even if I haven't done anything on this branch since a while, it is still useful.
