### ISSUE TITLE
Crash when changing address of j.send~ while audio is running

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#855]
The following crash happened when I changed the address of a j.send~ object while audio was running in the patch. This happened with the help file for j.send~. I have just updated it, and will commit a new version in a little while that can be used to experience this.

https://gist.github.com/lossius/921eefd22698d36befd5

**Comment by theod** [comment]
I just tried to change the address while audio running in j.send~.maxhelp and I don't get any crash.
is it possible this issue have been automagically fixed ? :-)

**Comment by theod** [comment]
still no crash on my side. I close the issue but feel free to reopen it if you still experience the crash.
