### ISSUE TITLE
other ramp values than global don't work in jcom.cuemanager

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#86]
when loading the cuelist file in a texteditor, and changing the value of a ramp from global to a numerical value (e.g. 2000), then the parameter ceases to ramp

 see more on the original redmine issue http://redmine.jamoma.org/issues/1491

**Comment by reno-** [comment]
j.cuemanager has been revamped, and global ramp does't exist anymore. So I'm closing this issue
