### ISSUE TITLE
jamoma_patcher_get_hierarchy doesn't return "poly" when it should

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#864]
if [j.model] is loaded inside a poly~ (at the topmost level of the poly),
`jamoma_patcher_get_hierarchy()` returns "topmost" instead of "poly"

**Comment by theod** [comment]
I tried with this simple patcher : 

<pre><code>
----------begin_max5_patcher----------
213.3ocQO1rBBCCDD9bxSQXOWKsU7G7UQDIVWzHoIkjzZEQe1MYSKdYgY1c1
Ol2bFbwNgdPbPbTvXu4LFYkLXyZFzImZ0ROcFXvm1KOfh7p.NEH6dq90WQmc
vikc1qnVrd4ldYn8txb6rCaCYTMaKqJDM6Sy5lMjnorRbZNhYH9ofFCDypYW
0UBUD+p5km6CuzHYC+ypLKQqSde37zf9NH66GQmWYMTISULVvGVWRtqfjJSV
RfAGNpVteC4HcwBEhsYvkYOseKjiFqtyLnlYGI+g+CvRaUk8
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
but it the only time it returns topmost is when is recursively analysing the context and arrive to the topmost patcher. otherwise all externals find they are inside a poly. maybe you fixed it ?

**Comment by avilleret** [comment]
I think I opened this issue after https://github.com/jamoma/JamomaMax/commit/a28dfb6ee742914c6900b0bc300e70da2c736e46

which seemed to not work as I expected.
Maybe it has been fixed since

**Comment by theod** [comment]
ok so I consider it is fixed
