### ISSUE TITLE
j.view : don't register if there is no second argument

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#865]
For now, when making a Jamoma module, I make a model with a j.model inside then a view with a j.view and then the module itself containing the others two.
I use the module's argument to name my view and my model. 
But I have to introduce a second argument to the view patcher to avoid some warnings.
This is quite annoying when I'm using only one view of a model.
After talking with @theod he said we shouldn't register a view which has only one argument.
So I assign this to him :-)

**Comment by theod** [comment]
I'll try to do this for 1.0

**Comment by theod** [comment]
ok so I've made this mechanism available for j.remote which reduces a lot the namespace.

I cannot do it for j.view as it needs to be into the namespace to allow j.remotes to bind on model:address an internal object registered under the j.view to handle the address of the model to bind. so there are still /mouse(view), /mouse(view)/model and /mouse(view)/ui but nothing more as I guess nobody used to pass 2 argument to j.remote.

is it ok ?

**Comment by theod** [comment]
I suppose it is ok. please reopen if it is not the case.
