### ISSUE TITLE
Some model preset messages can not be sent to the model, only directly

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#867]
Steps to reproduce:

1. Open help patch for j.model
2. In the Presets panel, there's a "j.send /spectral" object in the lower left part of the patch.
3. Change the value of the frequency/shift parameter. Result: frequency_shift gets updated.
4. Interpolate between presets using the "preset:interpolate..." message connected to "j.send /spectral". Result: Nothing happens.
5. Intepolate between presets using the "j.send /spectral/preset:interpolate" obejct in the upper right section of the patch. Result: Preset interpolation is taking place.

This issue relates to #733

**Comment by theod** [comment]
fixed !
it was due to a missing symbol conversion (to convert 'interpolate" into "Interpolate")
