### ISSUE TITLE
CMake : j.js_systeminfo.js is missing

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#868]
`j.js_systeminfo.js`is created from ` j.js_systeminfo.template.js` by ruby script
We have to do the same with CMake.

**Comment by reno-** [comment]
This is need for the 1.0 release because some patchers use this javascript, and generate errors if it's not present.

**Comment by reno-** [comment]
It was used only in two patchers, and I use max getsystem message instead of this javascript. So you can now postpone this issue to milestone 1.1
commit ddf45da8d9031c789338ac91de90cf398f8739d9

**Comment by avilleret** [comment]
what should Jamoma version and Jamoma rev look like ?
is the git tag the version and the git sha the revision ? (this is the simpliest)

**Comment by reno-** [comment]
Yes, you're right

**Comment by avilleret** [comment]
@reno- could you try this : https://github.com/jamoma/JamomaMax/tree/fix/868 ?

**Comment by reno-** [comment]
works perfectly… Bravo !!

**Comment by reno-** [comment]
I merged the branch into master… Tx @avilleret

**Comment by avilleret** [comment]
don't forget to also test the nightly build (both from Travis and from Appveyor) since the git tag / sha extraction mechanism is different

**Comment by reno-** [comment]
ahhh… JAMOMA_MAX_VERSION is missing in the last build for OSX (@GIT_TAG@).
But JAMOMA_MAX_REV is right (@GIT_SHA_SHORT@)

last build of windows has been done previously to your commit. I re-open the issue and I will double-check tomorrow

**Comment by avilleret** [comment]
actually this is an expected behavior since the tag is only defined on tagged commit on Travis.
And this could be the same on Appveyor.
We should wait for a tagged commit to see if it is correctly defined.
Until then, we could leave this issue open.
