### ISSUE TITLE
Max crash if "edit preset" window is open when closing a patch

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#874]
1. Open a new patch
2. Create a input~.module by typing shift + "i" in the patch
3. From the pop-up menu in juper left corner of the view, choose "Edit current preset"
4. Leave the text window open.
5. Close the patch (while the text window is still open).

This leads to the following crash:

https://gist.github.com/lossius/b4b75349bd5044f3b39e

**Comment by jln-** [comment]
FWIW, this also happens with j.cue text window

**Comment by theod** [comment]
reading at the Max SDK documentation it is not explain how to close the text editor window ourself ...
https://cycling74.com/sdk/MaxSDK-7.0.3/html/chapter_enhancements.html

I tried object_free but it doesn't work. maybe @tap knows more about this ?

**Comment by theod** [comment]
this have been fixed now.
it works well if you try to filter the value attribute.

<pre><code>
----------begin_max5_patcher----------
529.3ocyU00aaBCE8Y3WgkelkhgDBr2lzzdc+.pplbB2z5HvFYaxRWU+uO70
PJqccMjkT0G3Ce7UWetm6G9gv.5J0dvPIelbMIH3gvf.DxADzuNfVy2uthaP
yn0fwvuEnQ98L16q.biADYasPVAVz7jdvFtc8cB4s+PCqs9iisLYVbDIIdo6
SZ9bbUGF4lm7jp0N3JVOpnDON0psepX3L8lYuuA79lRI2314wvP2qnSK1rvd
jqzMhJKnuRH2nH63Usv2PfyfFjtX1hHRVlK1YrESWBxurRvoGZyyFkcYr3oG
ZYm4PSB+rysCNkKkJK2JTRbyu2ZaZsDWJVWivjMZUMoiilWVPfnypUkP0QpT
r+gREik9r3B2m7zoqTyem5Ct5+urnXTAeRg6+oEpoWzhhCQ51YRdmJzvWCmg
Db1n7aRb9ajfSeYTyd8nNp+4RLvy.1wy6HcToKnHeka4Dt0pEqZsf2h92wut
ZsQIsFwuPPlaz+oLOIk4KbxldSBKYLSboWbqunE7pirnBOLZkP97qLQ95v+S
s1nZ0qGb0.GHOw4RvXExCCgt9PxdjM2IJKAb6AEqTX3qp.Lxh+qI8ikNoenX
C6HXS2cBD16Bax+voMIuAaJNQswWUyaZ1AZSuKQhzMqXqR6VtLBWJj9knGoZ
XmXv94HBW200Z6ZYa09lq849KwotqJ0xVA1aF5N4GC+MKafagA
-----------end_max5_patcher-----------
</code></pre>

**Comment by tap** [comment]
For closing the window...

```
void text_wclose(t_text *x)
{
	defer(x,(method)text_dowclose,0,0,0);
}

void text_dowclose(t_text *x)
{
	if (x->t_Editor) {
		object_method(x->t_Editor, gensym("wclose"));
	}
}
```
where `x->t_Editor` is the `jed` instance ( i.e. `x->t_Editor = object_new(CLASS_NOBOX, gensym("jed"), x, 0);`
