### ISSUE TITLE
Websocket example

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#878]
Jamoma Websocket example crashes when clicking on `path` message box at the top left corner of the patch.

Here is the backtrace : https://gist.github.com/avilleret/821b9ba56b7617786ac5

**Comment by bltzr** [comment]
@laugre ?

**Comment by theod** [comment]
I assign to @jln- but he will certainly need the help of @laugre

**Comment by laugre** [comment]
Thank you for this fix @avilleret !
