### ISSUE TITLE
j.parameter : @default is ignored when specified before @type

### ISSUE THREAD

**Issue by matcham** [jamoma/JamomaMax#882]
<pre><code>
----------begin_max5_patcher----------
841.3ocyX00aZCCE8Y3WgUdZShgrcBAXOglV2K6gJsWmllbRLfaAGjsSKUU8
+97GIPXk.lTf1W.rw45y83y4dM7b2NAI4qox.vWA+Fzoyyc6zwNkYhNki6Dr
jrNcAQZWVPZ9xkTtJnm66Tz0J67ERFeFXxCjEET.iKUTRFHeJXRFcJoXgRul
a+Y0Ssfwoo4Eb6ihKmjWrLuPsfpraDrb1UDU5bcn+qflpb.EONtOrGHz8FZ.
zNJrOD7mxGhkYwTdxceAGWsoR0SKn14qlYkfJ04BQwx46D+nZwGV9xlfqwIi
WASjYtW5107Ru2HElqlSE.hRIXIEJpD7IAgOi1CjtfsZYdl9S862+yfueK3w
bw8fGmS4.0SqnYfD5zbAELwLZujb3oRxgPrIwwCqSxQCafjGbxjbHD4h+nqK
IypIIYRv2t4G29qabDWOPsufMiqYzryphEMXfOJ1nVnXqG+qKYZXNCgIWQSY
SYZw3TlPZ7642edXuMRQeHuvlIu2LMrjJkjYzWQCCB1aJgZNkFYOnhhsojKi
v38mQnwUQ2EZqE2FjffMq2akxng013CKTvsfgzAHgJ1OcfalNhrEbifwGmNv
vMYHQPVRUTweobRhK8gMRU8.AI5posfxhhqAtyu2hSeTmWuRScW+M4GP2KPE
V0ac.XRU+.PhtkAXhsKA.BPvJ2HWQms8XXG2Wzod1fP6zsEO17VbSmNnfCcB
zB1GgFcQaF2jmF1ROcXnOd5QsxS+9ZOKuJvQxr3Kl87J5zptGv6jWCG67ZgQ
GxqghZsW6h4ZPgmrsAgrY4PnGhK74rUXnqxB1s+Wfdg9I2P6Jj1J91xkdbS9
CIphb25zdeaDzcyiwMvvge7zTv1JovPezTn2oRw9oNv00CdTxo0pivwdHOFe
9UG1mwlC+2eCgEql42kDk4EhzpcsDSfsfMSyYLt0pWaMlCY.Zyhlyxxn75Mj
xXRSOJalB26oouvw3fNNdvWO7D4CdF8ACOw6rnKJdh8AOQWM7XtA8wwy3q14
kW3w7ixtV7CzG7fZIdbUiHqV8.UHKioEJ5h22kKLCG1yNjwcCsQLPPefUsda
I3.hPWoUoKyVHbUBWOxc03.ysIE7BVYkP8N+R2+AMrNBvB
-----------end_max5_patcher-----------
</code></pre>

**Comment by jln-** [comment]
Duplicates #837
