### ISSUE TITLE
j.namespace filter turns values to symbol

### ISSUE THREAD

**Issue by bltzr** [jamoma/JamomaMax#883]
in this case, we'd like to filter nodes with a integer value, which doesn't work because this value is turned into a symbol

see 
<pre><code>
----------begin_max5_patcher----------
565.3ocyUssaaCCC8Y6uBA8bVlkShcyda.C6mXsXPwlIQA1RFRzYoqn+6ylx
d0ooosC4R2CVFhhhhmygh5gv.9ByNvwYeg8CVPvCgAAjoVCAcyC3kxcYERG4
FWC+xrXCejeID1gj4BiLegTupeAccooFK.j1knypJmbtI.eRD06p2O79JvmG
bJNr65V1g2WPqvGDak94gtRhYqU5U+zBYnOPhnjwQiXh4zXTT6u33wQr6Z2x
iggsCiNMbWYUZTguLriND1y4mNrhS8vZ14.WkfyIWAG.rkpBDreVoWZXxLTs
E9NY40E3kFM5T+l.lnIk5QgEbfFknxnGfj3jXODH.E0M7Wke.skxGb.ZYom4
9pUIKNZYz6tDJ93b8TpBJYBklhzqJSyJM4.SoyJpa9KQzpVTiPmOrsxhZfcK
WbKm0PQMoL6aRTxbYqgRIa4dpUgRCYlZMNDu+SR3.w3lOHwHweQdFoFwozrI
ytLpgCv8EigT7QzBwdJF+DYYQ7GDMKtQ7TQ+jzjKQayMiaAjqRlcDdZxgDR7
wQ8ntuyviF9a7hnouVyU5bnKUO6sSJfs12mRblZaVe11+5G6oNc4fCUZp83.
mR2ym0p7bPO7YkbkStn.HFJ5E0lyZ5zVPdkxm1SJ9MRm4WsrI8cPN+ewMMcn
a5FcUpbhufji+ZlrpZKXccgjxjldLaL11ooinoJseJEQtE1p58mZjvk1l64X
yk7Zqusvtjob+VaZYa00JpsPX6I+X3e.GXYmDC
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
this is fixed !
