### ISSUE TITLE
j.receive @active 0 outputs value when address is changed

### ISSUE THREAD

**Issue by matcham** [jamoma/JamomaMax#884]
<pre><code>
----------begin_max5_patcher----------
681.3oc0V90jZBCD.+Y7SQFdouP4HIBh8oqeH5Sc5zIBQMNPhCD7zdy8cuaB
fh2gmzqhcJOfjk0M69a+C44INtKT64ktnuf9Nxw44INNVQFANMqcbyY6SxXk
V0bST44bo10q9cZ9dsU9Sq4RTxZlbkPtBwRSK3kkdnM9E7DtXGGUtVUkk9Io
FopzaqzHl7fdMnbqoxDRdhpRZsGsQXo9PF2tAspIqxACjw0V+InQ5VlNwXre
BamtNdnTpeT.bE4gvgw9z4v0TyyA9Adnoy7CP+n4uKRs6gZwlOSB5rSBY6Fg
MxdYxDyMuAxpb.ArU72vpG9lTKfPH8AsRqbGXnhajVKReXKuNNccOFF8PARb
3oHGS8mYdNzCMatABDR+P.G2KDH2PHzThf.RHFWDPCirgcbLj0mVS.BPfYuK
AhFcBfIiabimS8iMM.TH0ShNl5qq+uXfSteo9wu5Oh7AR8A2LBH4OAV7M.Xi
+VVAKmq4E15ezio7krpLMB7udmGRFHlHWDSdWcPg+qFQfCrEJzv9wT7MaN4P
nDTpbhRmpQ+m.onPCWtBdlM93IWkxybuSAMbGaJLlCwOo9SJwWtGJ5lE8Kpz
Zk7udLwB3jICdTAdZjenIBwvXi35Fh4cdr2yML9461iR8HKQa9M3xTYoRpWx
R3cOiz4jh1QyRwurZhgr46Vl38GLuMlbZRh0vWdfKsqaKgVd6q9ZgfkcUpZM
ncNvqNGq08LxOG0kpphj1fpc2Q3i9UJuTKjLs.J55nT7YJsVjlxkcgapnjs.
NRmUVuI8A6OPuCJ3Z9C8LkFU+gN.+gb+bmf+Cwi4CVenxm5pa11s63EkM1z5
JvHiMpByxYd1kBY8RqEcK36Ds5a6zcYEPypF5TqJpau1GWOj107YjBYknoyB
14Wl7av7W5C5
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
this is fixed !
