### ISSUE TITLE
j.cue: namespace/select doesn't work when j.minuit_device is instanciated

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaMax#891]
I'm not sure but if I open j.minuit_device.maxhelp and then I open j.model.maxhelp and go to the Priorities tab, the namespace selection result into an empty cue.

**Comment by jln-** [comment]
related to #879 ?

**Comment by bltzr** [comment]
I think so...

**Comment by theod** [comment]
a simple patcher that illustrates the problem : 

<pre><code>
----------begin_max5_patcher----------
800.3oc2WszaiBCD9b3WAhyro1FBO5sUZuu21KUqhbAmTGQrQFSa5Vs+2Wy3
3.IkzllzVUsW.y348Leyj7j2jfakaXMA9W6ei+jIO4MYBPpivjseOIXMcSQE
sAXKPvdPd6pfP6UZ1FMPd0z0bQKWOujcOuf4tuQ+XECXvQQzZXrhoAsg6IJa
0NpnsTqo5h63hkyUrBs0GwwSQg9jztm4H3LYJx+2akfWB1x3feKNnize875d
DdhA2ZVSCcI6YQmfZtolVvtpUzvpLti+Ug98TczLQQyNoq3BVgrU.pf3hIEq
gIzTMWJlOJGuRJyw1BoP2v+CvI1jCFS+84sn7tbENERbDbR2qnYCxb6WAb0E
KI8i0LqZBB1IvXEGRde0AGm8LiLz4FZlAksnfAwWWBFt46JNsxcyREsjyrIM
mFtcYgrRpr9AZ5Lxr37PyATBIMdFbBEkSHF+Zf+rUJxaVrE7pJPz4tbSuWMB
SvS7EXkK1M2K6PxQ37jNwhP4YnX6ICI7wU.Urz1URRQ6Z1FxPsRVKUtJqQg4
iokVsbX4ynpy.kdzQPEsu0AOGAEsOZfbTzP3ogHvoV.WxKNvJ80a82qLlmkS
lAkwXbZbBA5ChvYccDPY78b.H6AeX317FC7kE5yJ45fOxIVyhryphvSmsaj0
d4t2kQVIvRDr0JcuNzJmvLqjrWnx84uExTq9ArD95ut6iHvdbbB4SXeTZl0H
3yYeD4cYeDJNBGkByYShSQ.nEkGiwYu7BoSWtKZiz4XlK2Q+OdmDUHj8sUA+
rUW2p84hER0Zfr+Bkbs+dvycvbf5z0xRV0wmv10Ntv.5G96ke8Mbnirg6LwW
.HNAODjM9tM7nnnewTkTAc3HRPXXR0A+oDv7cz2uFzHaUENm0MK1u2GJYMZt
XWk3l9UsCX5NdYISLLSVxan2Vwf.X7tgS0eh9Z4NjOR2wV7n002yTMa0I3IF
nxJKTOMD9jKreBZLPY1V43OFnPUldMsoQqUYaU1jkDXE0.KTl+nIz050kC71
BONngYWW1JH2vTHz1tPSxRYv5GhoBV2Vo4tXpKZ79q2+..LXklO
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
the problem starts in TTCueManager::getNamespace().
if there is one application: the namespace don't have a level for the application name.
if there are several application: the namespace have a level for application names.

in the second case we need to prepend the application name to the address to select.
I'm looking for a solution that automatically takes care of this.

**Comment by theod** [comment]
ok it is fixed now !
