### ISSUE TITLE
setup Travis for Windows build

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#896]
could we build for Windows Max with Mingw-w64 on Linux ?
if so, then Travis could do that for us.

**Comment by avilleret** [comment]
Travis is failing to build for Windows with :

~~~~
../../source/c74support/max-includes/MaxAPI.lib: error adding symbols: File format not recognized
~~~~

See https://travis-ci.org/jamoma/JamomaMax for more details.

**Comment by jcelerier** [comment]
-- Check for working CXX compiler:
/home/travis/mingw-w64-install//bin/x86_64-w64-mingw32-g++ -- works

../../source/c74support/max-includes/MaxAPI.lib: error adding symbols: File
format not recognized


I think that this MaxAPI.lib is 32 bits; wouldn't you need
i686-w64-wingw32-g++ ?
I had made some work for win64 to work, but only with visual studio, not
with mingw...
The 64 bits windows Max SDK files are here :
https://github.com/jamoma/JamomaMax/tree/dev/source/c74support/max-includes/x64



-------
Jean-Michaël Celerier
http://www.jcelerier.name

On Mon, Jul 27, 2015 at 12:32 AM, Antoine Villeret <notifications@github.com

**Comment by avilleret** [comment]
nop, `i686-w64-wingw32-g++` is for targetting windows either 32 or 64 bit from Linux 32bit.
`x86_64-w64-mingw32-g++` is used to target WIndows 32 or 64 bit from Linux 64bit.
Maybe they should choose a more explicit name for that tool.

Btw, I'm using it with `-m32` option which tell it to target Windows 32bit, see :
https://github.com/jamoma/JamomaMax/blob/feature/mingw-w64/Shared/CMake/toolchains/mingw-w64.cmake#L10

Here is a bug report that might be related : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=787162
It seems to be fixed, but I don't know where.
I grab and build the latest source of mingw-w64 yesterday and it doesn't help.

Moreover, the same toolchain works for JamomaPureadata so I guess this is more a Mingw-w64 big than a configuration issue.

But I'll try to build some SDK example first with different version of mingw-w64 to see what's wrong.

**Comment by avilleret** [comment]
according to https://cycling74.com/forums/topic/compile-max-6-1-external-with-mingw-x64/ it seems that MaxAPI doesn't work with Mingw.
So I think this is not feasible and I'll go ahead with Appveyor config.
