### ISSUE TITLE
Travis CI OSX build

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#897]
Travis is building for OSX since today : https://travis-ci.org/jamoma/JamomaMax/builds
And push builds to https://github.com/jamoma/nightly-builds/tree/master
Could anyone test if the archive work ?

**Comment by bltzr** [comment]
maybe @thorangutang

**Comment by avilleret** [comment]
The uploaded archive are empty...

**Comment by avilleret** [comment]
Archive is fixed, now we need test

**Comment by reno-** [comment]
it works !!
I download the nightly build for OSX today and the package works smoothly.

I noticed that  the version number is missing when loading Max.
Max Console : 
Jamoma (build b2583e8)                        Version ..- | jamoma.org

**Comment by avilleret** [comment]
Thanks for the test.

Concerning empty tag, this is because it's a nightly build.
Tag only appear on tagged commit aka on release.
