### ISSUE TITLE
Can't load JamomaConfiguration.xml on Win64

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#899]
A fresh build under Visual Studio on Win64 displays the following error when launching Max 64 bit :

~~~~
Jamoma not loaded : can't find misc/JamomaConfiguration.xml
~~~~

according to https://github.com/jamoma/JamomaMax/blob/master/library/source/JamomaForMax.cpp#L95-L102, the error message should display the full path to the file.
So it seems that `TTFoundationBinaryPath` is not set as it should.

The same code works on Win32 so I may have miss something in the Cmake configuration step ?

**Comment by theod** [comment]
is @jcelerier able to help you ? it could be nice to fix this for the 1.0.

**Comment by jcelerier** [comment]
Mhh, maybe you could put a debug in `TTExtensionLoader.cpp` at the beginning of 
`bool TTWinSpecific::TTLoadExtensionsFromFolder(const string& folder)` to see where it tries to load the extensions from...

`TTFoundationBinaryPath` would be set after a successful extension loading.

**Comment by avilleret** [comment]
Afair it doesn't load any extension and that's why `TTFoundationBinaryPath` is empty.
So the issue should be : "can't load extension on Win64"

**Comment by avilleret** [comment]
related to #904

**Comment by tap** [comment]
In my note on #904 I was running on 32-bit, so it appears that the problem is not limited to 64-bit only.

**Comment by tap** [comment]
This issue is fixed.  There are additional problems on Windows, however...
