### ISSUE TITLE
jmod.mapperContinuous undesired behaviour when both ramping and bidirectional mode are on

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#90]
when both ramping and bidirectional mode are on, when we change the value of the first, it triggers the ramp in the second, which then feeds back to the first parameter causing it to jump back and ramp along. 

to reproduce:

1.open jmod.mapperContinuous.maxhelp
2.set 1st mapping parameter in mapper.1 to input~/audio/gain and the second to output~/audio/gain
3.set the mode to bidirectional
4.set the ramp to 1000 ms
5.change the value of input~/audio/gain slider and notice what happens.

I personally think that we should filter parameter feedback from the second parameter until the ramp is done. (btw. you need to check out latest changes from git to get the bidirectional mapping working first)

any thoughts?

Adrian 

 see more on the original redmine issue http://redmine.jamoma.org/issues/1486

**Comment by reno-** [comment]
bidirectionnal mode is dead… so the issue too
