### ISSUE TITLE
Use contemporary semver tags for versioning.

### ISSUE THREAD

**Issue by tap** [jamoma/JamomaMax#902]
E.g. `v1.0-beta.1`, `v0.5.7`, etc.

**Comment by tap** [comment]
Needs code review -- @avilleret , can you take a quick look?

I was not very thorough in the above commit.  From searching it appeared as though the only place any of this is used is in the post to the Max window where all we want to do is post the entire tag name.

In the event this code is used elsewhere, I was not comfortable mucking with the cmake source for setting all of the component parts.  Too bad cmake doesn't have a simple regex to do everything for us!

**Comment by avilleret** [comment]
I'm Ok with your commit.
The only thing is that GIT_TAG is not always defined (but this have been always the case).
When you clone without the entire history (with `git clone --depth 1 ...`) GIT_TAG is not defined.
Neither in `TRAVIS_TAG` nor in `git describe --always`.
This is why I added the short SHA to the print.

On CI, GIT_TAG is defined only when you tag a commit I think.
