### ISSUE TITLE
Install locations for DLLs on Windows 

### ISSUE THREAD

**Issue by tap** [jamoma/JamomaMax#903]
Hi @avilleret -- I'll assign to you since I think you know the most about how to handle this, but if you are too pressed for time then assign back to me and I'll do my best to not mess it up...

What currently happens is that all of our DLLs are placed into the top-level of the "support" folder in the Jamoma package.  This does not work, however, on systems where a user might use both 32- and 64-bit versions.

What needs to happen is that the `support` folder has two subfolders named `pc_win32` and `pc_x64` where each of the architecture-dependent DLLs are placed.

For example:

* Jamoma
    * support
        * pc_win32
            * AnalysisLib.ttdll
            * JamomaFoundation.dll
        * pc_x64
            * AnalysisLib.ttdll
            * JamomaFoundation.dll

FWIW, this support for FAT packages on Windows was just introduced in Max 7.0.6.

**Comment by avilleret** [comment]
could you test the commit above to check if it doesn't break Mac OS build ?
and merge it if it's ok
thanks

**Comment by avilleret** [comment]
it seems to work partially : https://ci.appveyor.com/api/buildjobs/vqupgmyypbr657vy/artifacts/JamomaMax-Windows_Win32-16abc13-.zip

btw, what about the externals folder ?
should we do the same ?

**Comment by avilleret** [comment]
Mac OS build seems to be unaffected

**Comment by tap** [comment]
Thanks @avilleret -- We don't need to do this with externs because they have different file extensions (mxe/mxe64) already.

**Comment by avilleret** [comment]
ho sorry I forgot that, so I close the issue since the fix is merged
