### ISSUE TITLE
Problems Starting on Windows

### ISSUE THREAD

**Issue by tap** [jamoma/JamomaMax#904]
There are (at least) 3 problems with trying to get Jamoma working initially on Windows:

1. Missing DLL error due to AudioEngine linked to PortAudio
2. Missing DLL error due to SoundfileLib linked to LibSndFile
3. `Jamoma not loaded : can't find C:\Users\tim\Documents\Max 7\Packages\Jamoma\support\pmisc/JamomaConfiguration.xml`

Regarding (1) I don't believe we should ship this with JamomaMax.  It is used in JamomaRuby and it is used in JamomaMax only in quarantined externals (e.g. `j.dac=` and `j.adc=`).  Because it is important for JamomaRuby I don't think we should completely quarantine it though.  So we need to strip it after building I guess?  Or is there a better way?  Perhaps @avilleret has an idea?

Regarding (2) I am uncertain if this is actually used anywhere in JamomaMax.  If not we could strip as I propose for (1).  The folks who might know if it is used or not are @nwolek @Nilson -- can you guys comment?

I'm not yet sure what to make of (3).  The separator between `support` and `misc` is suspicious looking.  Perhaps @theod can comment about it?

**Comment by Nilson** [comment]
Regarding (2): To my knowledge the SoundfileLib was/is only used in the j.soundfile.player= and j.soundfile.recorder= externals. They are not used in any of the models in the distro at the moment.
To have the option to store broadcast wave files, our ouput=.model should use our soundfile.recorder= rather than C'74s sfrecord~.

**Comment by tap** [comment]
@trond -- how do you feel about moving the `j.soundfile.player=` and `j.soundfile.recorder=` to quarantine?

**Comment by tap** [comment]
Yes, I produced (3) on win32.

**Comment by avilleret** [comment]
here is the screenshot with the short SHA : 
![image](https://cloud.githubusercontent.com/assets/504914/9616988/e9d6602e-5100-11e5-9517-c7da12064612.png)

It was on July the 29th I think.

**Comment by nwolek** [comment]
Trond might not have seen the question because his username is @lossius. Reposting

@tap asked - "how do you feel about moving the j.soundfile.player= and j.soundfile.recorder= to quarantine?" 

I am registering my +1

**Comment by tap** [comment]
Issues here have all been resolved as of the fix for #899.  Additional issues forth coming.
