### ISSUE TITLE
jmod.mapperContinuous logarithmic mode bug

### ISSUE THREAD

**Issue by hems** [jamoma/JamomaMax#91]
At certain settings of logarithmic mode, jcom.map in the jmod.mapperContinuous produces nan (not a number) which then fails to be clipped by the clip object which follows. 

to reproduce:

1.open jmod.mapperContinuous.maxhelp
2.set 1st mapping parameter in mapper.1 to input~/audio/gain and the second to output~/audio/gain
3.set function to logarithmic and coefficient to -2
4.set input~/audio/gain range in the mapper to 0 50
5.now tweak the gain slider on the input~ module: when you cross above 50 the output~/audio/gain drops to 'zero'(or rather nan :)

I think that the clipping of the input parameter should be done before jcom.map to avoid the above. If no one has any objections I'll go ahead and change it.

 see more on the original redmine issue http://redmine.jamoma.org/issues/1485

**Comment by reno-** [comment]
this is no more relevant with mapper.model…
