### ISSUE TITLE
CMake looks after Max framework into  /Library/Frameworks/  instead of using the repo's one

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#911]
I've cloned Jamoma Max according to the instructions in the ReadMe, and attempted to  build. However the build process stops with an error at j.model. The whole Terminal output from the git clone outwards is posted here:

https://gist.github.com/lossius/05fb40cf0eec0e44807a

Any hints on what I need to do to get this working?

**Comment by avilleret** [comment]
according to https://gist.github.com/lossius/05fb40cf0eec0e44807a#file-gistfile1-txt-L7777-L7779, it seems that you have an old 32bit Max framework in /Library/Frameworks/

This is a bug that this one takes precedence over the one included in the Github repo.
As a workaround you can try to remove it then CMake should find the on shipped in the repo.

**Comment by lossius** [comment]
I removed them, and it now compiles. Thanks!

This issue is solved for me, but I guess you'd like to solve it according to the new title, and hence I keep it open.

**Comment by lossius** [comment]
For what it's worth this libs might well have come as part of an earlier TapTools install.

**Comment by tap** [comment]
I don't think this would have come from TapTools.

Nothing should be linking (on the Mac) against MaxAPI nowadays.

Also, I'm not thrilled with everything linking against JitterAPI when we only have one or two objects that have anything to do with Jitter.
