### ISSUE TITLE
j.cue / preset : update : do not respect specified unit

### ISSUE THREAD

**Issue by matcham** [jamoma/JamomaMax#912]
if a unit has been specified in the cue / preset, the update function still get value in native unit (but keeps the unit name after the value).
When unit is specified : update should get value in this unit.

example patch :

<pre><code>
----------begin_max5_patcher----------
821.3oc0XssahCCD8Y3qvMO0UJvFmDBPk1p9ercUkIdJ31DmnXGJUU8ee8Mn
zVnaTZBhkGRTFeaNykyLlWFNvaQwFP3gtB8azfAuLbv.iHsfAtuG3kS1jlQD
lo4kCBAYI34aGSBajF4.kIQLNStcDg74LvLzVI75bFOCjlMJ7MgE0xsRwNok
DY5JFe4cUPpzpdQgiC7QwQy0ulDneFpDg9iaI1cQ9bIXmum2tgXTidTr3gQg
QdZYuNbn9geCAcZQdNvkeBzKfTRs.P0kThDPqHBzxJxhE.EsljUCJCBhSjr0
ponLM9HBmhdDfRIJmQYKILtORT3VOEkpVRZAWpjKPaOsLFGRKp4liLtYVW7A
stAG25hCLl2noX8K7jX8qjf8ru6aDC6Ri3nQWeMB8Ssw.ELdmgwqeQpKPB6h
jNFRC5VjN5ZzHbb7334H5BzEWbQOixnFgR77tDktjAcr7kKAoMS3G8GPsPaV
XS.5r1.ziQ4oTBRV1Ifzy4EmjzRRObRWBam+s+gsymlzZXOoKCqSWAoOhjqH
R0Ca3MSfrw.Jp6K+Uwi8VP97oFSPjgUFOO4Kiwi6Rmsispubz3.Cxlg+VE0w
Q+WlV67msOsF2FXeeVgRO81obUjbPBU2AbxBKHCNJpuunJmXvPRyiqCOtcXp
wiGkzXuuupmKBe4gMGcZsZS+r5j7qP2xqfxLRJrqIk.yua4OwjqbBU0g9TqK
uqysndka.mre8u3oGlanSK+ch532grVSNzo093vSmBHG98fbqp6oflZseBwO
LdGEAxDnei9zQTHkkSxP2n5EfHJ0IG1Q02yQ2a6MT3dRclTksbvzgvuS5vWP
ofilY3TbLrVBlI+KRkCeWwN0Lp3R75IL6tZ7baTSTy3QOLG59P1LAiW6C+CA
FUPK+81AQQcU51ivFG5idSKnfPxz2Ftfu2bvuaNqXTJv2mwixD55RFUL3f9i
lpMImUZCFedoNmW9J74kyJL57RcZh1Db5bVAMPeBOurNZGJtEpikSjTVtFpD
t8znIpp.OTTo+bpu4SF29oYGUWpXMa67mXjPpTz3REGdcksVvlYId1kVPgJd
MyTKXn9jec3eAvyE7KC
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
I've changed the milestone because 1.0/build is dedicated to CMake or other troubles relative to the build of the repository.

**Comment by theod** [comment]
this should be fixed now for j.cue and preset.
could you test it @matcham ?

**Comment by matcham** [comment]
something is broken 
if a line contains unit AND ramp message, it doesn't work as expected :
/gain 100. midigain ramp 5000

same problem if this message is send to a j.parameter directly :
100. midigain ramp 5000

(the ramp seems to start from specified value converted to native unit ... or something like that..)

**Comment by theod** [comment]
ok so this issue can be closed and you should open another one dedicated to this problem because it seems not related to j.cue or preset but to j.parameter.

**Comment by matcham** [comment]
ho.. sorry for the noise : no bug here : it works fine if the number box is disconnected from the input of j.parameter... (feedback loop)
