### ISSUE TITLE
j.view : Can it please just ignore bang?

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#925]
At times I like to embed views within views, and connect the embedded view to j.ui so that it can pop up as a panel with additional configuration options.

Whenever I do this, and then start using it, and hit the panel button in the upper right corner of the top-level view, the other view shows up as expected, but I also get the following error message posted to the Max window:

    j.view: doesn't understand "bang"

Could we add a bang() method to j.view that does nothing, just to get rid of this error message?

For an example, please check the help file for the dbap=.model.

**Comment by theod** [comment]
excellent idea ! it is done
