### ISSUE TITLE
j.ramp: List ramping does not work with varying number of list members

### ISSUE THREAD

**Issue by lossius** [jamoma/JamomaMax#935]
In the below patch:

* At the left side j.ramp is first set to a single float value. next it is requested to ramp as a list. Result: Nothing happens
* At the right side it is set to a list of same length as subsequent list. Result: Works as expected.

@theod - Do you have any idea if this is a bug in he max external or if it rather is a Core-related bug?

<pre><code>
----------begin_max5_patcher----------
426.3ocwUE0aBBCD9Y3WQSelQZQPw8WYwrTkKZMXgzVbZL9eevAD0M00YXtW
Zyc8528cebG8fuGcdwNvPIuRdi34cv2yCc03vqy1itQraQtvfgQ2.FiXIPCZ
OqTCFPYEVYg5cMrv1hURZTHKfDkD2rw5VHy5tkpZiTkCVDxnNmF69b.yA8TX
EU19338oTXWrRpVdszga73onUzYYTlgHWLe8Ki6guEa69RnEEJkLq4ji99MK
AOlhXgcHqnrv5ZtlMgjnPhVrojjvXL2DNdL6YJb7Qo3VTx8DtICrvofOpg8a
515vFwxQcZ5jeVm3NpSQ+rNMEEn336ISo2VlBFndrgtMHJYh6yOIOs4maN77
GU+8iAb98p+Q+GiACcCceE6RCM+WzPi2mlKUe8UEjCM9uTILEU5E8v08SFxI
VjAFqTgC+mES5EwrRlkA3wr9aIMh44.VArq9EwU1j5.apeOgveJrg6.aRdZr
YjCrg+feoZaiDkkaAsoCRjH0iNqKzMlSBPSop0DQjpgsx93GidD55Veaceek
tcTY23XZ6UKx.spRhST9MY9n+mvXowfY
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
it is in TTRamp.cpp at line 301 : 

        if (mNumValues == inputValue.size())

I can take care of it but it is strange for me to allow such kind of feature...

**Comment by theod** [comment]
I mean it will need to make complex code where it would be easier to prevent the user that he is doing something wrong. don't you think ?

**Comment by theod** [comment]
as I said before it seems to me this issue is not relevant.
should we close it ?

**Comment by lossius** [comment]
Yes, we can close it.
