### ISSUE TITLE
no more j.loader in JamomaMax nightly-builds

### ISSUE THREAD

**Issue by reno-** [jamoma/JamomaMax#938]
I download the latest build of the 8th october 2015, and j.loader is not present on the extensions subfolder of the Jamoma Package.

**Comment by avilleret** [comment]
it seems to be so since before september 7th

**Comment by avilleret** [comment]
after looking twice, I do have a j.loader.mxo in the extensions folder of http://jamoma.org/download/JamomaMax/nightly-builds/JamomaMax-2015-10-08-17-31-07-OSX-6ecd989-.tgz

from where did you download the package ?

**Comment by reno-** [comment]
I went on this page and tried the 3 builds of the 8th October 
http://jamoma.org/download/JamomaMax/nightly-builds
That's really really really strange...
I will try again tomorrow...

**Comment by reno-** [comment]
Sorry for the noise, j.loader is there… but i'm pretty sure it doesn't when I wrote this issue…
really really really strange…

**Comment by avilleret** [comment]
i see at least two reasons causing that : 
- you downloaded the archive while the build server was uploading it, then the download archive could be  corrupted
- you extracted the archive to a place you haven't full access (/tmp for example) then some errors occurred that were kept silent for sanity by Apple. (I have this experience when extracting the archive to /tmp with command line on Thor server, then some errors appear in terminal and no j.loader)
