### ISSUE TITLE
Windows: DLLs not installed to architecture-specific support locations

### ISSUE THREAD

**Issue by tap** [jamoma/JamomaMax#940]
Currently all DLLs are being thrown into the `support` folder in the package.

The should be instead installed to `support/pc_win32` and `support/pc_x64`.  This is required for packages to be merged into a FAT distribution.

**Comment by avilleret** [comment]
I remember to have work on this a while ago, maybe I forgot to test it...

**Comment by avilleret** [comment]
hopefully, I didn't dream here is the fix : https://github.com/jamoma/JamomaCore/tree/feature/windows_dll_folder

let me merge master into that branch to check build then merge back to master to fix this

**Comment by avilleret** [comment]
fixed with https://github.com/jamoma/JamomaMax/commit/c4482e671f799eeebc9a896045b60f2a31e4955b and https://github.com/jamoma/JamomaMax/commit/7ff27f3bb3947cbb7c6eed0c24ff8fa80270413b

**Comment by tap** [comment]
confirmed
