### ISSUE TITLE
don't expose useless nodes to Minuit

### ISSUE THREAD

**Issue by bltzr** [jamoma/JamomaMax#943]
it's unnecessary to expose some nodes to Minuit
so far, the ones we've pinned with @reno- are:
- most views -> we propose that all views that haven't been renamed by the user (i.e. are named *(view)) shouldn't be exposed
- all nodes that are not a Data (i.e. parameter, message, return) and don't have any Data child shouldn't be exposed

**Comment by theod** [comment]
for now I've simply hidden all nodes binding on a Container with service attribute equals to "view" during Minuit exploration.

is it ok for you ?

**Comment by theod** [comment]
I assign to you @bltzr but maybe @reno- can test it ?

**Comment by theod** [comment]
I've test it for a while and it works !
