### ISSUE TITLE
allow to bind to differents instances of a same model/view from j.ui

### ISSUE THREAD

**Issue by reno-** [jamoma/JamomaMax#947]
Different instances of the same models might be listed on this menu.
First line might be in grey, and two other lines in black with a tick on the right corresponding to the current model we're binding to.

Instead of 

    Model: /movie.1

We should have : 

    model/address : movie%.model
    /movie.1 ✔
    /movie.2
![capture d ecran 2015-10-28 a 10 28 34](https://cloud.githubusercontent.com/assets/127730/10784480/b0295da6-7d5e-11e5-9f1c-94fe49b9b7b1.png)

**Comment by theod** [comment]
this is a great request !
However I propose something a little bit different : 

Model class : movie%.model
/movie.1 ✔
/movie.2

as the first information is not the model address to bind but the class of models we want to bind.

**Comment by reno-** [comment]
you're right. 'Model class' instead of 'Model/address'.
I agree :-)

**Comment by theod** [comment]
ok. I'm currently working on it ! 
prepare your self for testing soon :-)

**Comment by theod** [comment]
still not ready but you'll have to test using feature/ui_select_model branch

**Comment by theod** [comment]
I've made something that seems to work well (https://github.com/jamoma/JamomaMax/commit/94bb9414381b2a927d8dea6e1cb5b52044b14713)

could you test it @reno- ?

**Comment by reno-** [comment]
Yes, it works, but I think  there is some side-effect

Here is a crash log I can reproduce.
https://gist.github.com/reno-/d01e51d2b1152a75b443

Edit a view that is instancied in a patcher
save it -> crash

**Comment by theod** [comment]
fixed !

**Comment by reno-** [comment]
It could be nice to have the first model of the list selected first. It's not the behavior on my computer
Here is a patch to test. This is movie.3 or movie.2 which is selected first.

What do you think about merging into master?

<pre><code>
----------begin_max5_patcher----------
460.3oc2T00SCBCE8Y3WQSS7MD4iIi3+BM9lwXJvcaUKsKkxbKF+ua6sfhYy
nwo9fj.jdt2x8dNG58ov.ZkZKzQIWPtgDD7TXP.B4.BFVGPaYaqErNLMpDdT
UcOMxGhIkJCyvURL3U.qgb40jV0FNPVvEswiYZfsFLGL1IwspFPPNCWEmMlk
p2H.iY2Zv2STZj8lb6P30LS8Jtb4cZn13yHsHNIhTNON2dkUFQRyKcHYYwIu
tOdCVZaie5qkR12xk1hgzJ6MPeK7NzNyNA1PTpC34vP2inunhUgcMn+.MSpj
vXHqV73FdGuhK3lctvoiByhEcv.kSb7KYB8Dp5GflFMaYWsVIDtzRFhUK30O
XVoU8KWMEGjrJArZ+M3CrY+.UKcd16PT5FKulfru+8l2ogNP5I9D+ajLQj7D
7U5roT6PNdYtKuYke3llX2meP6dTUkrVX5OkN8O1Zd1pRO3eDoeC++W4DS5w
dhwKeexgkz+7CK+Jh0riUrRKJ9BpU9+C0J+nUqrh3B607rOUxl8iIY3WmxVu
dCn6Fj.TyrJ18JbH07HbIW5WhCAnZvMv0mONEixzVZYrbpW6Ky1xBpeqVYRK
64CSBrU94vW.tM4ui.
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
I agree even if I'm not sure it is easy to do.

however if you didn't experience any crash I'm fine to merge it into master.

**Comment by theod** [comment]
hum ... finally it could be easier than expected ... I'm on it

**Comment by theod** [comment]
but I was wrong ...
for now this is depending on the order of creation of element into the patchers.
I need to create another method based on jamoma_patcher_get_model_patcher but with some advanced option to check the first argument.

for now a work around is to give the name of which model to bind first in argument to the view (and maybe this is a more hackable behavior don't you think ?). I let you open another issue for this feature request.

**Comment by theod** [comment]
I've merged it into master

**Comment by reno-** [comment]
yes, giving an argument sounds perfect. Tx
