### ISSUE TITLE
Add a :init item in top-left j.ui menu

### ISSUE THREAD

**Issue by reno-** [jamoma/JamomaMax#948]
Add an item 'init' that will send a :init message to the current model.
It could be add just before or after the presets items.

**Comment by jln-** [comment]
Depending on the final initialization implementation, maybe it should show up when there is no preset (or no default preset)

**Comment by reno-** [comment]
From what I remember about new initialization process, send the :init message to a model will launch the entire initialisation process in a cascading way : 
default-value -> then preset. 
a preset will overwrite a default value, and of course only one value should be outputed.

**Comment by theod** [comment]
for now, as the initialization process we discussed together is not ready, I propose that option only does what j.model init message does currently (so the default preset will not be launched).

**Comment by reno-** [comment]
yes @theod , that's the idea. It's a button to send the :init message to the model. So the :init message to the model will stay the same when the init mechanism will evolve, and nothing will be break !!

**Comment by theod** [comment]
I'll start to work on this of the feature/ui_select_model branch

**Comment by theod** [comment]
you can test it !

**Comment by reno-** [comment]
Perfect !
