### ISSUE TITLE
television%.model.maxhelp crash 

### ISSUE THREAD

**Issue by reno-** [jamoma/JamomaMax#950]
Just open the help, and max crash

    Thread 54 Crashed:
    0   libsystem_kernel.dylib        	0x00007fff8e071286 __pthread_kill + 10
    1   libsystem_c.dylib             	0x00007fff8c23f9b3 abort + 129
    2   libsystem_malloc.dylib        	0x00007fff904c2fe2 szone_error + 625
    3   libsystem_malloc.dylib        	0x00007fff904bc374 small_free_list_remove_ptr + 154
    4   libsystem_malloc.dylib        	0x00007fff904bb2a8 szone_free + 2696
    5   libsystem_malloc.dylib        	0x00007fff904ba43a szone_memalign + 819
    6   com.cycling74.chromium        	0x0000000107da6376 0x107c35000 + 1512310
    7   libsystem_malloc.dylib        	0x00007fff904ba0d6 malloc_zone_memalign + 114
    8   libobjc.A.dylib               	0x00007fff904f2166 (anonymous namespace)::AutoreleasePoolPage::autoreleaseNoPage(objc_object*) + 98
    9   libobjc.A.dylib               	0x00007fff904d7b69 objc_autoreleasePoolPush + 92
    10  com.apple.CoreFoundation      	0x00007fff8683e6a6 _CFAutoreleasePoolPush + 22
    11  com.apple.Foundation          	0x00007fff8f23f00f -[NSAutoreleasePool init] + 16
    12  com.cycling74.Max             	0x000000010708ece2 cocoa_utils_outputdebugstring + 50
    13  com.cycling74.Max             	0x0000000106e0c1a1 cpost + 246
    14  com.cycling74.Max             	0x0000000106e10ece c74_debug_malloc_footer_test + 147
    15  com.cycling74.Max             	0x0000000106e10f1d sysmem_freeptr_imp + 31
    16  com.cycling74.MaxAPI          	0x00000001160e5594 sysmem_freeptr + 36
    17  com.cycling74.JitterAPI       	0x000000011a4be3d4 jit_parallel_ndim_multi + 1163
    18  com.cycling74.JitterAPI       	0x000000011a4d60aa parallel_worker_execute + 40
    19  com.cycling74.JitterAPI       	0x000000011a4d62d6 parallel_threadproc + 49
    20  com.cycling74.Max             	0x0000000106e7561c systhread_threadproc + 64
    21  libsystem_pthread.dylib       	0x00007fff8fb9a05a _pthread_body + 131
    22  libsystem_pthread.dylib       	0x00007fff8fb99fd7 _pthread_start + 176
    23  libsystem_pthread.dylib       	0x00007fff8fb973ed thread_start + 13

**Comment by theod** [comment]
this one doesn't seem to be related to Jamoma.
Maybe you should ask on the Max forum what is going wrong here ?

**Comment by reno-** [comment]
oups, sorry. I thought it was an external.
