### ISSUE TITLE
j.namespace_explorer unusable

### ISSUE THREAD

**Issue by cbossut** [jamoma/JamomaMax#956]
The explorer is really a good thing, but the fact that everything is expanded makes it unusable.
It should be possible to expand all or reduce all in one click, and possibly remembering the state on refresh.
@theod told me that was @jln- task :-)

**Comment by reno-** [comment]
We use the dict.view Max object for this explorer, and from what I know, it is not possible to remote it with messages. We're dependant to the max object, so I don't think we can change this behavior until Cycling74 implements messages to expand or reduce parts of the dict.

**Comment by theod** [comment]
and I would suggest you to use the great namespace explorer of i-score ! ;-)
