### ISSUE TITLE
j.cue : how to store remote model value ?

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#973]
is it possible to store remote parameter value into j.cue ?

I would like to bind j.cue to a remote node with `[namespace/unselect /, namespace/select remote:/node(`
but it doesn't seem to work, or I may have miss something.

**Comment by avilleret** [comment]
here is a patch that demonstrate what I try to do :
https://gist.github.com/avilleret/17b35299c03d4efd47e5

it works with `examples/remote communication/minuit/remoteMinuitApp.maxpat`

**Comment by avilleret** [comment]
as a workaround, I made a bridge between a remote parameter and a local one then, I save the local parameter to update the remote one

here is an example : 

<pre><code>
----------begin_max5_patcher----------
797.3ocyWsjbhCCDcMbJT4MYCArr7GbVM2f4.L0ToTr6PLksjGI4DRkJ2mYN
G4hM5iIPRvNPXfwK.UciPc+dR8umFOx6F9JP5gtB8CznQOMdzHqJihQsxi7p
nqxJoR617x3UU.S4Mw8aJXkxp+6LDCP0PiBUSkHfIfEERk.DnRPp0InUu7as
rDkq0SYJIhdOjgVNMqAP4bVFhyP2RKTnFFpluwFkELHi2vrFJrUIqopfUBJq
WgaUVSUY2UvVbs.xTNTgChSm5OAMOkXVvQQlkX+o9ne19uJxsHfeyxKw9y81
X.diZsE7a0JUOVB1s6YT773wlulbjjG6k+jARIsPnoPdi.wtXaB7WMWXnjWo
PuCkCHAIFTGFFaVBhbKcxAwmRNfAOnsxGnfRNM+FJag2ge+FsE1LWrZnEzEz
B2MzVa.mJ0i0f6z8rtzqG0wg7JyU7B3CPWCFZYIRdGsFt12OXmTPPOTPDYtA
0QoVvi8C5mCvGHGblwO9vwefM1NJd+vevvF+9GN98c2+j8C+j+S3uiH+kSEP
EWAnLNb6se03+4X2BoOrm1wS+vNg9js9blngEbwBNCtDe0rbA8AMbmcTLSRh
80ANs2TiyiGxTis1Gnz0BsTA5aFGAQEB5ie4GLQ19Bvt1C5hVRR2MsDzKsbh
SXvzbgrllAyZXRnTCMzrInMZWqq6mMA6QA0DWnTb+QToCrjo5mPGQkTRrM2Y
zbayDoQ8B8vALzO7hnjPaOhQQ6CzICXne30OID2sdv9.8fgV0S83Se4RCtFm
Hw8VYH3DjBz9y1I6d2zmVu0n+sTgTOUT1ZC7Zq7nMNbNHUELppfy1ZWlzSas
o6JxyA11yxnmEkdSIXQq+NuU1eGBuGNjgLOaNTvPygHCKGxzNHB+Y9S7m3OU
E407BlRtN1Rm.YNgPRB0MY3RphChv1dNdqXRbrSLIbZTq3Fu4eFLeGB5HRAe
9n8zA1yfvAl+LzBSNo4QbUBn002CBY6YZcEc4ukbgQLYhUrf4Dsmndp46KVu
+XqFpPWmSoKx0HbEbV0NTiWEOGDrlBaYwwFK+73+BT9NWqH
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
this has been fixed with https://github.com/jamoma/JamomaCore/commit/c4ceedc12cc9547c9c52acc06fe65e1b874b7b99

it seems you were the first attempting to do this ! 
I assign you for tests

**Comment by avilleret** [comment]
this is my biggest fault : trying to do thing you'd never imagine :-)
btw, it works ! thanks @theod !
