### ISSUE TITLE
some models don't respect outlet order convention

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaMax#977]
j.model outlet should be connected to the rightmost outlet of a model while all the signals outlets should connected to the left ones.

I've noticed this trouble in movie.model but maybe a review should be done before the release.

**Comment by theod** [comment]
I've put it into 1.0/documentation milestone as the review should be done for all models and maxhelps in order to have a consistent way of patching into the distro.

**Comment by reno-** [comment]
fix #977

**Comment by theod** [comment]
sorry the one I've noticed (movie.model) is part of GMEA user lib ! 
so maybe this issue is not relevant ...
