### ISSUE TITLE
j.cue : names doesn't output anything when j.cue is empty

### ISSUE THREAD

**Issue by avilleret** [jamoma/JamomaMax#979]
while I'm expecting it to ouput [names( (without anything after names)
so that we know it's empty

**Comment by theod** [comment]
j.cue currently returns "names" when it is empty.
it is possible to catch this empty case using [sel bang] or [route bang].

<pre><code>
----------begin_max5_patcher----------
491.3oc0W01aCBBD9y5uBCe1snXUq6uxxxBpjNZrXCfcsYY+2Gdf8kko0YVc
aePHbbb2yiObWqu45fxq2SkHuG7dzyw4MWGGvTqAG6ZGzFx9hJhDbCk2nT0b
juYKdyl5FUEUAaFZsZLoNrkZhLJmvWg7dxt8Vhp3EFe0yBZgx3wh.78A9dQg
wsS3EciGOCqDxdc956BS5xtTcnBRA5L7v3GgSqs2ccaG7GI83zW04nKbJ5d.
fHglRTOfFeIyw8wbju9YDLGmtrcJAFw3dXd5HYNdBL+1HrQ3rwKrwyuvJoUS
QVMG4JRqk6VoMNYPoM5emzhyBLzK85Ra1uUIKmrQ2e6Gtlsi4X3Rsk+8HrKu
g5plZRxJ52TXGlZ3vynVbvPTKc9n1QUc.8bZDNLA5+FFAkmKFTKuk0n8bKd8
8EMze56ucbN0LEjMXmoIT5BwAUw3e9+V.fo09kuIj0MhhN3aqZ7NglRpTw3D
ES2D6jOs+Z3YN8BqrjB6GzcLljjWQApD7kRxXgymRUO3IY9vSzXvS7rgmQIW
Q+ofS17IV5LEdEzr7OEZRuvmaIZF083I9twzDhrc6NpPZCI.Dci200h1ko9v
RF2rDhHRP2w57OArPD5NnJc6yFgoA39kluAAsotjJ3MLaCPcle28CbqJA.I
-----------end_max5_patcher-----------
</code></pre>

**Comment by avilleret** [comment]
oups sorry for the noise...
btw I'd like to see Max smart enough one day to say that an empty list have a length of 0, but that would be in another world I think ;-)
