### ISSUE TITLE
User-facing ReadMe and License files

### ISSUE THREAD

**Issue by tap** [jamoma/JamomaMax#983]
Currently we have a ReadMe.md for developers.  We do not have one in the produced package for users.

Similarly we have a LICENSE for developers.  We do not have a file in the produced package, thus making things unclear in our distribution.

I'm not sure how urgent or non-urgent this task is for any/all of us...

**Comment by theod** [comment]
I would say sooner is the better so I can take care of this issue.

what kind of informations should be into the ReadMe.md ? 
should we guide beginners to the Extras > Overview patcher ?

**Comment by theod** [comment]
and about the license is the file should be named License.md ?
as a first draft is the following text would be ok ?

Jamoma is licensed under the terms of the "New BSD License" (http://creativecommons.org/licenses/BSD/)

**Comment by tap** [comment]
For the License, yes on the file name.  For the content I suggest following the model of the Jamoma2 license:

https://github.com/jamoma/jamoma2/blob/master/LICENSE.md

Though obviously we are using BSD instead of MIT

**Comment by tap** [comment]
I'm not sure what should be in the readme.  I guess a link to the website.  Maybe the change log should be there too?  But nobody is maintaining that?  So maybe it should be removed?  Or ???

**Comment by theod** [comment]
I've put a link to http://www.jamoma.org/max/ webpage into the ReadMe and adding a licence file replacing MIT by BSD.
