### ISSUE TITLE
parameters named after a node ignored from cue

### ISSUE THREAD

**Issue by jln-** [jamoma/JamomaMax#995]
parameters whose name are also a parent node in the namespace get their value ignored from a cue. 

This can be tested with the example patch below with a simple mapper model that contains the following:

`/map.1/input <parameter address to store>`
`/map.1/input/going.down/action.1`
`/map.1/input/going... etc.`

Set a state for your mapper then store a cue using cue_manager.model. '/map.1/input/going.down/action.1' value does get stored in the cue but '/map.1/input' is not.

This is reproducible using Jamoma latest nightly-build from 31 of December. 

<pre><code>
----------begin_max5_patcher----------
614.3oc6VtsbaBCDF9Z7SgFcssKBric588onSmLBXMVIBIFIgOLYRe1qN.I3
wPhsSunclbCG1Unc029qU77jHbl7.nwnui9IJJ54IQQdSNCQsuGgqnGx4Tse
X3rZpIeKnvSCNoBgzPMLov6VHEPmqcLX+Nllkw3LyQmaRqG4lMZvDBa773ot
Kne05jKyeBJJTzRctRx4tgE25KmyxexrUIaJ212NHnYbX64ePvwtycjUVIKf
SrHUE10UOK9kJST9fBxay1z6Sb4ax50taow9rmrZYu7mU3IgL6wYq5PgfV4i
ENuAdnhJnkfZtiOysv0FltwUq.MHB7rWT6XzHQTzTwDbvn6m7VixFyqVcFeY
xD2koeUpuhRsG01aK8Y+p3gqz20Qh.yMGqgvrfwuUl5DAEPohV.+9lT.CkHm
H.HCJ.HeI.tQAPpu9uHfcR7Ha0WdMBfJZc8M1.Xv7Xv5OUU11YG+Ma.mSv8G
+mTZHf81U8HBieT0voF.Y1BnFMfjaPb4dPgzzpZNLSYcpQTQAJiYlYWwRdi6
im2MeF3f4zcJtBHGIjL8Q73ULBIrW8Ne2YRx89d0ICWwVLZESyJETNdZ+mdC
dZyQdnLhGB+ICx3z+1LFJXFDEY2BhLR+sBpghbJKKSNCjsJt.FcpgjK.ijfT
KI88vX53B+qAaC20J4eMrQ9XrsN4BnVx+UTqem9WYS+ekI.HXms0k9iITxBR
3jr0uGhHWPG0aBO8624mIrsJuCT51kqmOV57nzeBwpo9WYhvq94Dq.2ocgw6
OBw1t0tZM1kZiJjQGVG9o.rCNJQCqM11H+xj+byfRuD
-----------end_max5_patcher-----------
</code></pre>

Setting all available red labels on this one. :-)

**Comment by theod** [comment]
fixed ! you have to update JamomaCore
