### ISSUE TITLE
j.map make integer truncation after setting clipmode attribute

### ISSUE THREAD

**Issue by theod** [jamoma/JamomaMax#996]
<pre><code>
----------begin_max5_patcher----------
618.3ocuVEraiBCD8L4qvhyrrFSHjrm5+Q0pHC3PbDXirMsopp+6q8XPjtg1
jlplKX6gYFOuwumgWWDDVHOxzgn+fdDED75hf.vjyPvv5fvV5wxFpFbKrT11
xDlvH+6LriFvNcmgoPc858bQMxrmqQZlw3WvPsztN27ZISidVIE0iYngKXkx
dAjFxfQdEjTYwgekO5XG0T5R9VEqz3K4k37XbDJYUFLjgcCoowXzeGBRadog
A4ZLMh9VtngY.3jLYT1aFshcFeawB2inqruzxzZZM6r9RYCuqUVwPERy9vyg
WB4SvWpEeYVfkicCqATRHm.OeQadoi4CHL7ZQNYVjO1OpUzJNyelLZqntT1H
U9MBGmudYZxxH6rjkY3MqcyvjzLxFaAeRINDF4qG2NdSCD61Q.NUWy3D7L46
rMe+B8ccHxFbxlUtvRsgiW5mYMk7wIfJp8mZjbGY9bG5TxNoxvkBfoFmtYtr
zajmdDdKDZA6YK+7L97gXqTF8fkyz0a9sMBTBIOdx.WXKJzCbw3pjoUVmwwy
p6yNWX7Y5BRJnKHj0ftOAjG4q9TgQzWPbL+0BjaoK12VvTyo6ytL9RIfh2es
1Ez8V3UXIOSPripnsL6kxaYBZgGs36M720HsIYN3iuL7Gt16d.+cRUKE18U2
VCA1WfS+eeMEfmy966RZYupbr5Gn6nI.Vwz1OcRGk4ONwYNwo87pJl3TfUw0
NrV8wZ9qsbRtl5gb+JG7OX43O6r+fxSLkdHkPkX4xG7WmmGAK4B+RHigJ1S7
Q+AZSHUYoxFKOtW44WGWuJzGp8W.ThdNvlV3142V7OfLTCzR
-----------end_max5_patcher-----------
</code></pre>

**Comment by theod** [comment]
it was because the clip bounds was not reversed when min was greater than max

**Comment by jln-** [comment]
(clap)
